import { ApiError } from "./admin-users.js";

const messages: Record<string, string> = {
  LOCAL_IDENTITY_REQUIRED: "Sign in to continue.",
  MEMBERSHIP_REQUIRED: "Your account does not have an active WorkshopOS membership.",
  PLATFORM_CREDENTIAL_REQUIRED: "A platform credential is required.",
  BRANCH_FORBIDDEN: "You do not have access to that branch.",
  PERMISSION_DENIED: "You do not have permission to perform this action.",
  IDEMPOTENCY_KEY_REQUIRED: "The request could not be retried safely. Try again.",
  IDEMPOTENCY_KEY_REUSED: "This retry belongs to a different change. Try again.",
  SUMMARY_REQUIRED: "Enter a work item summary.",
  REASON_REQUIRED: "Enter a reason for this command.",
  VERSION_REQUIRED: "Refresh the work item and try again.",
  VERSION_CONFLICT: "This work item changed since you opened it. Refresh and try again.",
  WORK_ITEM_NOT_FOUND: "The work item was not found or is no longer available.",
  EXPORT_NOT_FOUND: "The export was not found or is no longer available.",
  EXPORT_NOT_READY: "The export is still being prepared. Try again shortly.",
  EXPORT_FORMAT_INVALID: "Choose PDF or XLSX export format.",
  VIEW_MODE_INVALID: "Choose grid or table view.",
  NOT_FOUND: "The requested resource was not found.",
  EMAIL_EXISTS: "A user with that email already exists.",
  ROLE_NAME_REQUIRED: "Enter a role name.",
  ROLE_NAME_TOO_LONG: "Role names must be 100 characters or fewer.",
  ROLE_DESCRIPTION_TOO_LONG: "Role descriptions must be 500 characters or fewer.",
  ROLE_NAME_EXISTS: "A role with that name already exists.",
  ROLE_NOT_FOUND: "The role was not found or is no longer available.",
  ROLE_IN_USE: "Remove this role from every user before archiving it.",
  PROTECTED_ROLE: "Protected role templates cannot be changed or archived.",
  PERMISSION_INVALID: "Choose permissions from the current catalog.",
  PAGE_PERMISSION_REQUIRED: "Select a page permission before selecting its actions.",
  ARCHIVE_REASON_REQUIRED: "Enter a reason for archiving this record.",
  CUSTOMER_NAME_REQUIRED: "Enter a customer name.",
  MOBILE_INVALID: "Enter a valid 10-digit mobile number.",
  DUPLICATE_MOBILE: "That mobile number already belongs to another customer. Open the existing record or use a different number.",
  CUSTOMER_NOT_FOUND: "The customer was not found or is no longer available.",
  VEHICLE_IDENTITY_REQUIRED: "Enter a registration or VIN.",
  VIN_INVALID: "Enter a valid 17-character VIN.",
  DUPLICATE_REGISTRATION: "That registration already belongs to another vehicle. Open the existing record instead.",
  DUPLICATE_VIN: "That VIN already belongs to another vehicle.",
  OWNER_ASSOCIATION_INVALID: "Choose an active customer from the same branch.",
  OWNERSHIP_DATE_CONFLICT: "This vehicle already has an ownership change for today. Review its ownership history before trying again.",
  VEHICLE_NOT_FOUND: "The vehicle was not found or is no longer available.",
  EXPORT_SCREEN_INVALID: "Choose the customer or vehicle export.",
  IMPORT_FILENAME_REQUIRED: "Enter the source filename for this inventory import.",
  IMPORT_ROWS_INVALID: "Add between 1 and 1,000 inventory rows.",
  IMPORT_VALIDATION_FAILED: "Resolve every rejected inventory row before committing.",
  IMPORT_REFERENCE_CHANGED: "An inventory item or warehouse changed after validation. Stage the import again.",
  INVENTORY_IMPORT_NOT_FOUND: "The inventory import was not found or is no longer available.",
  IMPORT_HAS_NO_ERRORS: "This inventory import has no rejected-row manifest.",
  INVENTORY_POSITION_NOT_FOUND: "The inventory item or warehouse is not available in your scope.",
  QUANTITY_INVALID: "Enter a positive inventory quantity with no more than six decimal places.",
  VALUE_MINOR_INVALID: "Enter a non-negative whole value within the supported currency range.",
  JOB_NOT_FOUND: "The Job was not found or is no longer available in your permitted branches.",
  JOB_DOCUMENT_NOT_FOUND: "The Job document was not found, is not final, or is no longer available.",
  LIFECYCLE_COMMAND_INVALID: "That lifecycle action is not valid for the Job's current state. Refresh and review the available actions.",
  LIFECYCLE_BLOCKED: "Resolve the listed Job lifecycle blockers before trying this action.",
  LIFECYCLE_EVIDENCE_REQUIRED: "Add evidence for this acceptance or clearance fact.",
  VISIT_DATE_REQUIRED: "Choose a Visit/check-in date.",
  VISIT_DATE_INVALID: "Choose a valid Visit/check-in date.",
  MEDIA_JOB_NOT_FOUND: "Choose a Job from the selected Visit date and permitted branches.",
  MEDIA_LABEL_REQUIRED: "Enter a label for this media item.",
  MEDIA_CATEGORY_INVALID: "Choose a supported media category.",
  MEDIA_CATEGORY_STAGE_INVALID: "That media category is not available at the Job's current lifecycle stage.",
  MEDIA_FILE_INVALID: "Choose a JPEG, PNG, or PDF file up to 20 MB.",
  MEDIA_UPLOAD_FAILED: "The private media upload did not complete. Choose the file and try again.",
  MEDIA_NOT_FOUND: "The media item was not found in your permitted branches.",
  MEDIA_NOT_AVAILABLE: "The original is quarantined, archived, or unavailable in your permitted branches.",
  MEDIA_OBJECT_NOT_FOUND: "The private media original could not be retrieved.",
  MEDIA_SCAN_RESULT_INVALID: "The scanner returned an invalid result.",
  MEDIA_SCAN_NOT_PENDING: "This media item is no longer waiting for a scan result.",
  SCANNER_AUTHORITY_REQUIRED: "Trusted scanner authority is required.",
  ESTIMATE_NOT_FOUND: "The Estimate was not found in your permitted branches.",
  ESTIMATE_TOTAL_INVALID: "Enter a non-negative Estimate total in minor currency units.",
  ESTIMATE_VALIDITY_INVALID: "Choose an Estimate validity from 1 to 90 days.",
  ESTIMATE_NOT_DRAFT: "Only the current draft Estimate can be edited or submitted.",
  ESTIMATE_NOT_ACTIONABLE: "This Estimate is expired, decided, or otherwise unavailable for approval.",
  ESTIMATE_SUPERSEDED: "A newer Estimate version exists. Open that version to continue.",
  ESTIMATE_JOB_MISMATCH: "The selected prior Estimate belongs to a different Job.",
  ESTIMATE_DOCUMENT_NOT_FOUND: "The selected submitted Estimate document is unavailable.",
  APPROVAL_EVIDENCE_REQUIRED: "Record the approving customer and acknowledgement evidence.",
  TASK_NOT_FOUND: "The Task was not found in your permitted branches.",
  TASK_ACTION_INVALID: "That Task action is not valid for its current status.",
  TASK_ASSIGNEE_REQUIRED: "Only an assigned technician may execute this Task or add its evidence.",
  TASK_LIFECYCLE_BLOCKED: "Task execution is available only while the Job is in active work.",
  JOB_ON_HOLD: "Resume the Job before changing work or QC records.",
  TASK_DEPENDENCY_BLOCKED: "Complete the Task dependencies before starting this Task.",
  TASK_EVIDENCE_REQUIRED: "Add every required clean checklist evidence item before completing the Task.",
  TASK_EVIDENCE_INVALID: "Choose a checklist item and verified clean Job Media evidence.",
  VERIFIED_CLEAN_EVIDENCE_REQUIRED: "Choose clean, non-archived Media linked to this Job.",
  TECHNICIAN_REQUIRED: "Choose a technician.",
  TECHNICIAN_INVALID: "Choose an active technician from the same branch.",
  QC_TASK_NOT_FOUND: "The QC Task was not found in your permitted branches.",
  QC_NOT_ACTIONABLE: "This QC Task is not ready for an inspection decision.",
  QC_LIFECYCLE_BLOCKED: "QC actions are available only while the Job is in QC.",
  INDEPENDENT_QC_REQUIRED: "QC must be completed by someone who did not perform the Task.",
  INDEPENDENT_REINSPECTION_REQUIRED: "Reinspection must be completed by someone other than the rework technician.",
  INVALID_QC_CHECKLIST: "Complete every QC checklist result and note.",
  FAILED_QC_ITEM_REQUIRED: "A failed QC decision must identify at least one failed item.",
  REWORK_NOT_FOUND: "The rework record was not found in your permitted branches.",
  REWORK_NOT_ASSIGNABLE: "This rework record is not available for assignment.",
  REWORK_NOT_ASSIGNED_TO_ACTOR: "Only the assigned rework technician may complete this rework.",
  REWORK_EVIDENCE_REQUIRED: "Choose verified clean Job Media evidence before completing rework.",
  REWORK_ACTION_INVALID: "That rework action is not valid for its current status.",
  BILLING_STAGE_REQUIRED: "Move the Job to Billing before finalizing its invoice.",
  APPROVED_ESTIMATE_REQUIRED: "Approve an Estimate before finalizing the invoice.",
  APPROVED_ESTIMATE_LINE_REQUIRED: "The approved Estimate has no invoiceable scope.",
  INVOICE_ALREADY_FINALIZED: "This Job already has an immutable final invoice.",
  FINAL_INVOICE_REQUIRED: "Finalize the invoice before recording payment.",
  WORK_ACCEPTANCE_STAGE_INVALID: "Work acceptance is available only during Billing or Gate Verification.",
  WORK_ACCEPTANCE_EVIDENCE_REQUIRED: "Record the accepting customer and acknowledgement.",
  WORK_ALREADY_ACCEPTED: "Work Accepted has already been recorded for this Job.",
  PAYMENT_INVALID: "Enter a positive payment amount, mode, and unique reference.",
  PAYMENT_STAGE_INVALID: "Payments are available only during Billing or Gate Verification.",
  PAYMENT_EXCEEDS_BALANCE: "The payment exceeds the exact outstanding invoice balance.",
  PAYMENT_NOT_FOUND: "The payment was not found in your permitted branches.",
  INVOICE_NOT_FOUND: "The final invoice was not found in your permitted branches.",
  CORRECTION_INVALID: "Enter a positive correction amount and accountable reason.",
  CORRECTION_EXCEEDS_PAYMENT: "The correction exceeds the original payment.",
  CORRECTION_EXCEEDS_INVOICE: "The correction exceeds the final invoice amount.",
  CORRECTION_NOT_FOUND: "The correction request was not found or is no longer pending.",
  MAKER_CHECKER_SEPARATION_REQUIRED: "A different authorized person must approve this correction.",
  RELEASED_FINANCE_LOCKED: "Finance cannot be corrected after vehicle release.",
  DELIVERY_EVIDENCE_INVALID: "Complete the odometer, recipient identity, and delivery acknowledgement.",
  DELIVERY_EVIDENCE_STAGE_INVALID: "Record delivery acknowledgement while the Job is in Billing.",
  RELEASE_BLOCKERS_REMAIN: "Resolve invoice, exact payment, acceptance, and delivery blockers before release.",
  GATE_PASS_STAGE_INVALID: "Generate the gate pass while the Job is in Billing.",
  GATE_PASS_EXPIRY_INVALID: "Choose a future gate-pass expiry.",
  GATE_PASS_NOT_FOUND: "The gate pass was not found in your permitted branches.",
  GATE_VERIFICATION_STAGE_REQUIRED: "Move the Job to Gate Verification before vehicle release.",
  GATE_VERIFICATION_EVIDENCE_REQUIRED: "Capture scanner or accountable manual verification evidence.",
  VEHICLE_RELEASE_REQUIRED: "Independently verify and release the vehicle before closing the Job.",
  REQUEST_BODY_TOO_LARGE: "The request is larger than WorkshopOS accepts.",
  INTERNAL_ERROR: "WorkshopOS could not complete the request. Try again.",
};

export type PublicApiError = {
  status: number;
  body: { code: string; message: string; traceId: string };
};

export function publicApiError(error: unknown, traceId: string): PublicApiError {
  const duplicateEmail = (error as { code?: string }).code === "23505";
  const status = error instanceof ApiError ? error.status : duplicateEmail ? 409 : 500;
  const code = error instanceof ApiError ? error.code : duplicateEmail ? "EMAIL_EXISTS" : "INTERNAL_ERROR";
  return { status, body: { code, message: messages[code] ?? messages.INTERNAL_ERROR, traceId } };
}
