import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { Client } from "pg";
import { PostgresVertical, type Membership } from "../local/database.js";

const adminUrl=process.env.INVENTORY_TEST_ADMIN_URL,appUrl=process.env.INVENTORY_TEST_APP_URL;
test("inventory analytics are full-filtered and staged imports commit once with exact append-only reconciliation",{skip:!adminUrl||!appUrl?"isolated PostgreSQL URLs not supplied":false},async()=>{
  const tenant="80000000-0000-4000-8000-000000000001",branch="80000000-0000-4000-8000-000000000011",otherBranch="80000000-0000-4000-8000-000000000012",member="80000000-0000-4000-8000-000000000101",warehouse="80000000-0000-4000-8000-000000000501",otherWarehouse="80000000-0000-4000-8000-000000000502";
  const seed=new Client({connectionString:adminUrl});await seed.connect();try{await seed.query("INSERT INTO workshopos.tenant(tenant_id,legal_name,plan_id,entitlements,quotas,base_currency,timezone,configuration_template_id) VALUES($1,'Inventory Workshop','pilot','[]','{}','INR','Asia/Kolkata','india-v1')",[tenant]);await seed.query("INSERT INTO workshopos.branch(id,tenant_id,name) VALUES($2,$1,'Delhi'),($3,$1,'Jaipur')",[tenant,branch,otherBranch]);await seed.query("INSERT INTO workshopos.membership(id,tenant_id,identity_subject,email,display_name,status,cognito_username,active) VALUES($2,$1,'inventory-user','inventory@test.invalid','Inventory User','ACTIVE','inventory@test.invalid',true)",[tenant,member]);await seed.query("INSERT INTO workshopos.inventory_warehouse(tenant_id,branch_id,id,name) VALUES($1,$2,$4,'MAIN'),($1,$3,$5,'OTHER')",[tenant,branch,otherBranch,warehouse,otherWarehouse]);await seed.query("INSERT INTO workshopos.membership_inventory_warehouse(tenant_id,membership_id,branch_id,warehouse_id) VALUES($1,$2,$3,$4)",[tenant,member,branch,warehouse]);for(let index=1;index<=26;index++)await seed.query(`INSERT INTO workshopos.inventory_item(tenant_id,branch_id,id,category_id,sku,base_uom,stock_uom,purchase_uom,issue_uom,costing_method,tax_code,reorder_point,tracking) VALUES($1,$2,$3,$4,$5,'EA','EA','EA','EA','MOVING_AVERAGE','GST18',5,'NONE')`,[tenant,branch,`80000000-0000-4000-8000-${String(600+index).padStart(12,"0")}`,randomUUID(),`PART-${String(index).padStart(2,"0")}`]);
    // Reuse item identity in another branch: movement correlation must not leak its newer timestamp.
    await seed.query(`INSERT INTO workshopos.inventory_item(tenant_id,branch_id,id,category_id,sku,base_uom,stock_uom,purchase_uom,issue_uom,costing_method,tax_code,reorder_point,tracking) SELECT tenant_id,$1,id,category_id,'OTHER-PART',base_uom,stock_uom,purchase_uom,issue_uom,costing_method,tax_code,reorder_point,tracking FROM workshopos.inventory_item WHERE branch_id=$2 AND sku='PART-01'`,[otherBranch,branch]);
  }finally{await seed.end();}
  const actor:Membership={id:member,subject:member,tenantId:tenant,branchIds:[branch],warehouseIds:[warehouse]};const db=new PostgresVertical(appUrl);try{
    const first=await db.queryInventory(actor,{search:"PART",branchId:"",sort:"summary.asc",page:1,pageSize:25});assert.equal(first.inventory.length,25);assert.equal(first.page.totalCount,26);assert.equal(first.analytics.skuCount,26);assert.equal(first.analytics.reorderCount,26);
    const invalid=(await db.stageInventoryImport(actor,{branchId:branch,filename:"bad.csv",rows:[{sku:"MISSING",warehouseCode:"MAIN",quantity:"1",valueMinor:"100"}]},"stage-bad")).import;assert.equal(invalid.summary.invalidRows,1);assert.equal((await db.queryInventory(actor,{search:"PART-01",branchId:"",sort:"summary.asc",page:1,pageSize:25})).inventory[0].quantity,"0");assert.match((await db.downloadInventoryImportErrors(actor,invalid.id)).content.toString(),/SKU_NOT_FOUND/);await assert.rejects(()=>db.commitInventoryImport(actor,invalid.id,{version:1},"commit-bad"),(error:any)=>error.code==="IMPORT_VALIDATION_FAILED");
    const staged=(await db.stageInventoryImport(actor,{branchId:branch,filename:"good.csv",rows:[{sku:"PART-01",warehouseCode:"MAIN",quantity:"2",valueMinor:"100"},{sku:"PART-02",warehouseCode:"MAIN",quantity:"3",valueMinor:"120"}]},"stage-good")).import;assert.equal(staged.summary.validRows,2);const committed=await db.commitInventoryImport(actor,staged.id,{version:1},"commit-good");assert.deepEqual(committed.reconciliation,{ledgerBatches:2,quantity:"5.000000",valueMinor:"220"});const replay=await db.commitInventoryImport(actor,staged.id,{version:1},"commit-good");assert.equal(replay.replay,true);
    const verify=new Client({connectionString:adminUrl});await verify.connect();try{await assert.rejects(()=>verify.query("DELETE FROM workshopos.inventory_ledger_entry WHERE tenant_id=$1",[tenant]),/append-only/);}finally{await verify.end();}
  }finally{await db.close();}
});
