server {
    listen 80;
    listen [::]:80;

    root /app/dist;
    index index.html;

    location = /sw.js {
        add_header Cache-Control "no-cache" always;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
