import { createHash, randomUUID } from "node:crypto";
import { Pool, type PoolClient } from "pg";

import { ApiError, type AuthenticatedMembership } from "../src/admin-users.js";
import { requireRecentMfa, requireReason, type EmulationContext, type PlatformPrincipal } from "../src/platform-admin.js";

export class PlatformDatabase {
  readonly pool: Pool;
  constructor(connectionString = process.env.DATABASE_URL) {
    if (!connectionString) throw new Error("DATABASE_URL is required");
    this.pool = new Pool({ connectionString, max: 5 });
  }

  async principal(identityId: string, mfaAuthenticatedAt: string): Promise<PlatformPrincipal | undefined> {
    const client = await this.pool.connect();
    try {
      await client.query("BEGIN");
      await client.query("SELECT set_config('app.platform_identity_id',$1,true),set_config('app.platform_permissions','',true)", [identityId]);
      const row = (await client.query<{ identity_id:string;display_name:string;permissions:string[] }>("SELECT identity_id,display_name,permissions FROM workshopos.platform_identity WHERE identity_id=$1 AND active", [identityId])).rows[0];
      await client.query("COMMIT");
      return row ? { identityId:row.identity_id,displayName:row.display_name,permissions:row.permissions,mfaAuthenticatedAt } : undefined;
    } catch (error) { await client.query("ROLLBACK"); throw error; } finally { client.release(); }
  }

  async session(principal: PlatformPrincipal) {
    return this.inScope(principal, async client => ({ principal:{ identityId:principal.identityId,displayName:principal.displayName,permissions:principal.permissions }, tenants:(await client.query<any>("SELECT tenant_id id,legal_name name,plan_id plan,timezone,version::text FROM workshopos.tenant ORDER BY legal_name,tenant_id")).rows.map((row:any)=>({...row,version:Number(row.version)})) }));
  }

  async tenantScope(principal: PlatformPrincipal, tenantId: string) {
    return this.inScope(principal, async client => {
      const tenant=(await client.query<any>("SELECT tenant_id id,legal_name name,plan_id plan,timezone,version::text FROM workshopos.tenant WHERE tenant_id=$1",[tenantId])).rows[0];
      if(!tenant)throw new ApiError(404,"TENANT_NOT_FOUND");
      const branches=(await client.query<any>("SELECT id,name,active FROM workshopos.branch WHERE tenant_id=$1 ORDER BY name,id",[tenantId])).rows;
      const users=(await client.query<any>("SELECT id,display_name,email,status,active FROM workshopos.membership WHERE tenant_id=$1 AND status<>'ARCHIVED' ORDER BY lower(display_name),id",[tenantId])).rows;
      return {tenant:{...tenant,version:Number(tenant.version)},branches:branches.map(row=>({id:row.id,name:row.name,active:row.active})),users:users.map(row=>({id:row.id,displayName:row.display_name,email:row.email,status:row.status,active:row.active}))};
    });
  }

  async listSupportGrants(principal:PlatformPrincipal,tenantId:string){if(!tenantId)throw new ApiError(422,"TENANT_SCOPE_REQUIRED");return this.inScope(principal,async client=>({grants:(await client.query<any>("SELECT support_grant_id id,tenant_id,support_identity_id,branch_ids,permissions,reason,status,requested_by,approved_by,approval_reason,approved_at,version::text,requested_at,expires_at FROM workshopos.platform_support_grant WHERE tenant_id=$1 ORDER BY requested_at DESC",[tenantId])).rows.map(this.mapGrant)}));}

  async requestSupportGrant(principal:PlatformPrincipal,input:Record<string,unknown>){requireRecentMfa(principal);const reason=requireReason(input.reason);const tenantId=String(input.tenantId??""),supportIdentityId=String(input.supportIdentityId??""),branchIds=Array.isArray(input.branchIds)?[...new Set(input.branchIds.map(String))]:[],permissions=Array.isArray(input.permissions)?[...new Set(input.permissions.map(String))]:[];if(!tenantId||!supportIdentityId||!branchIds.length||!permissions.length||permissions.some(value=>value!=="tenant.emulate"))throw new ApiError(422,"SUPPORT_SCOPE_REQUIRED");const expiresAt=new Date(String(input.expiresAt??""));if(!Number.isFinite(expiresAt.getTime())||expiresAt<=new Date()||expiresAt.getTime()>Date.now()+24*60*60_000)throw new ApiError(422,"SUPPORT_EXPIRY_INVALID");return this.inScope(principal,async client=>{const supportIdentity=(await client.query("SELECT 1 FROM workshopos.platform_identity WHERE identity_id=$1 AND active",[supportIdentityId])).rowCount;if(!supportIdentity)throw new ApiError(422,"SUPPORT_IDENTITY_INVALID");const valid=(await client.query("SELECT count(*)::int count FROM workshopos.branch WHERE tenant_id=$1 AND id=ANY($2::uuid[]) AND active",[tenantId,branchIds])).rows[0].count;if(valid!==branchIds.length)throw new ApiError(422,"BRANCH_SCOPE_INVALID");const id=randomUUID();const row=(await client.query<any>(`INSERT INTO workshopos.platform_support_grant(support_grant_id,tenant_id,support_identity_id,branch_ids,permissions,reason,status,requested_by,authentication_context,requested_at,expires_at) VALUES($1,$2,$3,$4::uuid[],$5::text[],$6,'PENDING',$7,$8::jsonb,transaction_timestamp(),$9) RETURNING support_grant_id id,tenant_id,support_identity_id,branch_ids,permissions,reason,status,requested_by,approved_by,approval_reason,approved_at,version::text,requested_at,expires_at`,[id,tenantId,supportIdentityId,branchIds,permissions,reason,principal.identityId,JSON.stringify({mfa:true,authenticatedAt:principal.mfaAuthenticatedAt}),expiresAt])).rows[0];return {grant:this.mapGrant(row)};});}

  async approveSupportGrant(principal:PlatformPrincipal,id:string,input:Record<string,unknown>){requireRecentMfa(principal);const approvalReason=requireReason(input.reason);return this.inScope(principal,async client=>{const current=(await client.query<any>("SELECT * FROM workshopos.platform_support_grant WHERE support_grant_id=$1 FOR UPDATE",[id])).rows[0];if(!current)throw new ApiError(404,"SUPPORT_GRANT_NOT_FOUND");if(current.requested_by===principal.identityId)throw new ApiError(409,"DISTINCT_APPROVER_REQUIRED");if(current.status!=="PENDING")throw new ApiError(409,"SUPPORT_GRANT_NOT_PENDING");if(new Date(current.expires_at)<=new Date())throw new ApiError(410,"SUPPORT_GRANT_EXPIRED");const row=(await client.query<any>(`UPDATE workshopos.platform_support_grant SET status='ACTIVE',approved_by=$1,approval_reason=$2,approval_authentication_context=$3::jsonb,approved_at=transaction_timestamp(),version=version+1 WHERE support_grant_id=$4 RETURNING support_grant_id id,tenant_id,support_identity_id,branch_ids,permissions,reason,status,requested_by,approved_by,approval_reason,approved_at,version::text,requested_at,expires_at`,[principal.identityId,approvalReason,JSON.stringify({mfa:true,authenticatedAt:principal.mfaAuthenticatedAt}),id])).rows[0];return {grant:this.mapGrant(row)};});}

  async requestEmulation(principal:PlatformPrincipal,input:Record<string,unknown>){requireRecentMfa(principal);const reason=requireReason(input.reason);const grantId=String(input.grantId??""),tenantId=String(input.tenantId??""),membershipId=String(input.membershipId??""),branchId=String(input.branchId??"");if(!grantId||!tenantId||!membershipId||!branchId)throw new ApiError(422,"EXACT_EMULATION_SCOPE_REQUIRED");return this.inScope(principal,async client=>{const grant=(await client.query<any>(`SELECT * FROM workshopos.platform_support_grant WHERE support_grant_id=$1 AND tenant_id=$2 AND support_identity_id=$3 AND status='ACTIVE' AND transaction_timestamp()<expires_at FOR UPDATE`,[grantId,tenantId,principal.identityId])).rows[0];if(!grant||!grant.branch_ids.includes(branchId)||!grant.permissions.includes("tenant.emulate"))throw new ApiError(403,"ACTIVE_SUPPORT_GRANT_REQUIRED");const member=(await client.query("SELECT 1 FROM workshopos.membership m JOIN workshopos.membership_branch mb ON mb.tenant_id=m.tenant_id AND mb.membership_id=m.id WHERE m.id=$1 AND m.tenant_id=$2 AND m.active AND m.status='ACTIVE' AND mb.branch_id=$3",[membershipId,tenantId,branchId])).rowCount;if(!member)throw new ApiError(422,"EFFECTIVE_SCOPE_INVALID");const id=randomUUID();const row=(await client.query<any>(`INSERT INTO workshopos.platform_emulation(emulation_id,support_grant_id,tenant_id,effective_membership_id,branch_id,requested_by,reason,status,request_authentication_context,requested_at) VALUES($1,$2,$3,$4,$5,$6,$7,'PENDING',$8::jsonb,transaction_timestamp()) RETURNING *`,[id,grantId,tenantId,membershipId,branchId,principal.identityId,reason,JSON.stringify({mfa:true,authenticatedAt:principal.mfaAuthenticatedAt})])).rows[0];return {emulation:this.mapEmulation(row)};});}

  async approveEmulation(principal:PlatformPrincipal,id:string,input:Record<string,unknown>){requireRecentMfa(principal);const approvalReason=requireReason(input.reason);return this.inScope(principal,async client=>{const current=(await client.query<any>("SELECT * FROM workshopos.platform_emulation WHERE emulation_id=$1 FOR UPDATE",[id])).rows[0];if(!current)throw new ApiError(404,"EMULATION_NOT_FOUND");if(current.requested_by===principal.identityId)throw new ApiError(409,"DISTINCT_APPROVER_REQUIRED");if(current.status!=="PENDING")throw new ApiError(409,"EMULATION_NOT_PENDING");const row=(await client.query<any>(`UPDATE workshopos.platform_emulation SET status='APPROVED',approved_by=$1,approval_reason=$2,approved_at=transaction_timestamp(),approval_authentication_context=$3::jsonb,version=version+1 WHERE emulation_id=$4 RETURNING *`,[principal.identityId,approvalReason,JSON.stringify({mfa:true,authenticatedAt:principal.mfaAuthenticatedAt}),id])).rows[0];return {emulation:this.mapEmulation(row)};});}

  async listEmulations(principal:PlatformPrincipal,tenantId:string){if(!tenantId)throw new ApiError(422,"TENANT_SCOPE_REQUIRED");return this.inScope(principal,async client=>({emulations:(await client.query<any>("SELECT * FROM workshopos.platform_emulation WHERE tenant_id=$1 ORDER BY requested_at DESC",[tenantId])).rows.map((row:any)=>this.mapEmulation(row))}));}

  async startEmulation(principal:PlatformPrincipal,id:string){requireRecentMfa(principal);return this.inScope(principal,async client=>{const current=(await client.query<any>(`SELECT e.*,g.status grant_status,g.expires_at grant_expires_at FROM workshopos.platform_emulation e JOIN workshopos.platform_support_grant g ON g.support_grant_id=e.support_grant_id WHERE e.emulation_id=$1 FOR UPDATE OF e`,[id])).rows[0];if(!current)throw new ApiError(404,"EMULATION_NOT_FOUND");if(current.requested_by!==principal.identityId)throw new ApiError(403,"EMULATION_REQUESTER_REQUIRED");if(current.status!=="APPROVED"||!current.approved_by||current.approved_by===principal.identityId)throw new ApiError(409,"EMULATION_APPROVAL_REQUIRED");if(current.grant_status!=="ACTIVE"||new Date(current.grant_expires_at)<=new Date())throw new ApiError(410,"SUPPORT_GRANT_EXPIRED");const row=(await client.query<any>(`UPDATE workshopos.platform_emulation SET status='ACTIVE',started_at=transaction_timestamp(),expires_at=transaction_timestamp()+interval '15 minutes',version=version+1 WHERE emulation_id=$1 RETURNING *`,[id])).rows[0];return {emulation:this.mapEmulation(row)};});}

  async resolveEmulation(principal:PlatformPrincipal,id:string):Promise<{membership:AuthenticatedMembership;context:EmulationContext}|undefined>{return this.inScope(principal,async client=>{const e=(await client.query<any>(`SELECT e.* FROM workshopos.platform_emulation e JOIN workshopos.platform_support_grant g ON g.support_grant_id=e.support_grant_id WHERE e.emulation_id=$1 AND e.requested_by=$2 AND e.status='ACTIVE' AND transaction_timestamp()<e.expires_at AND g.status='ACTIVE' AND transaction_timestamp()<g.expires_at`,[id,principal.identityId])).rows[0];if(!e)return undefined;const m=(await client.query<any>(`SELECT m.id,m.tenant_id,m.identity_subject,m.email,m.display_name,m.status,m.version::text,coalesce(jsonb_agg(DISTINCT jsonb_build_object('id',r.id,'name',r.name,'permissions',r.permissions)) FILTER(WHERE r.id IS NOT NULL),'[]') roles,coalesce(array_agg(DISTINCT p.permission) FILTER(WHERE p.effect='ALLOW'),'{}') direct_allow,coalesce(array_agg(DISTINCT p.permission) FILTER(WHERE p.effect='DENY'),'{}') direct_deny FROM workshopos.membership m LEFT JOIN workshopos.membership_role mr ON mr.membership_id=m.id AND mr.tenant_id=m.tenant_id LEFT JOIN workshopos.role_template r ON r.id=mr.role_id AND r.tenant_id=m.tenant_id LEFT JOIN workshopos.membership_permission p ON p.membership_id=m.id AND p.tenant_id=m.tenant_id WHERE m.id=$1 AND m.tenant_id=$2 AND m.active AND m.status='ACTIVE' GROUP BY m.id`,[e.effective_membership_id,e.tenant_id])).rows[0];if(!m)return undefined;const rolePermissions=(m.roles as any[]).flatMap(role=>role.permissions as string[]),deny=new Set<string>(m.direct_deny),permissions=[...new Set([...rolePermissions,...m.direct_allow])].filter(value=>!deny.has(value));const branch=(await client.query<any>("SELECT id,name FROM workshopos.branch WHERE id=$1 AND tenant_id=$2 AND active",[e.branch_id,e.tenant_id])).rows[0];if(!branch)return undefined;const warehouseIds=(await client.query<{warehouse_id:string}>("SELECT warehouse_id FROM workshopos.membership_inventory_warehouse WHERE tenant_id=$1 AND membership_id=$2 AND branch_id=$3",[e.tenant_id,m.id,e.branch_id])).rows.map(row=>row.warehouse_id);const membership:AuthenticatedMembership={id:m.id,tenantId:m.tenant_id,identitySubject:m.identity_subject,email:m.email,displayName:m.display_name,status:m.status,roleIds:(m.roles as any[]).map(role=>role.id),roles:m.roles,branchIds:[e.branch_id],branches:[branch],permissions,version:Number(m.version),warehouseIds};return {membership,context:{emulationId:e.emulation_id,platformActorId:principal.identityId,effectiveMembershipId:m.id,tenantId:e.tenant_id,branchId:e.branch_id,expiresAt:e.expires_at.toISOString()}};});}

  async recordEmulatedAction(principal:PlatformPrincipal,context:EmulationContext,method:string,route:string,status:number|undefined,traceId:string){return this.inScope(principal,async client=>{const phase=status===undefined?"REQUEST":"RESULT";await client.query(`INSERT INTO workshopos.platform_emulated_action(action_id,emulation_id,tenant_id,branch_id,platform_actor_id,effective_membership_id,method,route,phase,response_status,trace_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)`,[randomUUID(),context.emulationId,context.tenantId,context.branchId,principal.identityId,context.effectiveMembershipId,method,route,phase,status??null,traceId]);});}

  async logs(principal:PlatformPrincipal){return this.inScope(principal,async client=>({logs:(await client.query<any>(`SELECT l.log_id id,l.log_date,l.object_key,l.content_type,l.checksum_sha256,l.online_until,l.recoverable_until,CASE WHEN transaction_timestamp()<=l.online_until THEN 'ONLINE' WHEN transaction_timestamp()<=l.recoverable_until THEN 'RECOVERABLE' ELSE 'EXPIRED' END tier,EXISTS(SELECT 1 FROM workshopos.platform_log_recovery r WHERE r.log_id=l.log_id AND r.restored_until>transaction_timestamp()) restored FROM workshopos.platform_daily_log l ORDER BY log_date DESC,log_id`)).rows.map(this.mapLog)}));}
  async downloadLog(principal:PlatformPrincipal,id:string,reasonValue:unknown,traceId:string){const reason=requireReason(reasonValue);return this.inScope(principal,async client=>{const row=(await client.query<any>(`SELECT l.*,CASE WHEN transaction_timestamp()<=l.online_until OR EXISTS(SELECT 1 FROM workshopos.platform_log_recovery r WHERE r.log_id=l.log_id AND r.restored_until>transaction_timestamp()) THEN true ELSE false END available FROM workshopos.platform_daily_log l WHERE log_id=$1`,[id])).rows[0];if(!row)throw new ApiError(404,"LOG_NOT_FOUND");const checksum=createHash("sha256").update(row.content).digest("hex");const deniedCode=!row.available?"LOG_RECOVERY_REQUIRED":checksum!==row.checksum_sha256?"LOG_CHECKSUM_MISMATCH":undefined;if(deniedCode){await client.query("INSERT INTO workshopos.platform_log_access_audit(audit_id,log_id,platform_actor_id,action,reason,outcome,trace_id) VALUES($1,$2,$3,'DOWNLOAD',$4,'DENIED',$5)",[randomUUID(),id,principal.identityId,reason,traceId]);return {deniedCode};}await client.query("INSERT INTO workshopos.platform_log_access_audit(audit_id,log_id,platform_actor_id,action,reason,outcome,trace_id) VALUES($1,$2,$3,'DOWNLOAD',$4,'ALLOWED',$5)",[randomUUID(),id,principal.identityId,reason,traceId]);return {content:row.content as Buffer,mimeType:row.content_type as string,filename:`workshopos-${row.log_date.toISOString().slice(0,10)}.ndjson`};});}
  async recoverLog(principal:PlatformPrincipal,id:string,reasonValue:unknown,traceId:string){const reason=requireReason(reasonValue);requireRecentMfa(principal);const result=await this.inScope(principal,async client=>{const row=(await client.query<any>("SELECT * FROM workshopos.platform_daily_log WHERE log_id=$1",[id])).rows[0];if(!row)throw new ApiError(404,"LOG_NOT_FOUND");const now=new Date();const checksum=createHash("sha256").update(row.content).digest("hex");const deniedCode=now>row.recoverable_until?"LOG_RETENTION_EXPIRED":checksum!==row.checksum_sha256?"LOG_CHECKSUM_MISMATCH":undefined;if(deniedCode){await client.query("INSERT INTO workshopos.platform_log_access_audit(audit_id,log_id,platform_actor_id,action,reason,outcome,trace_id) VALUES($1,$2,$3,'RECOVERY_REQUESTED',$4,'DENIED',$5)",[randomUUID(),id,principal.identityId,reason,traceId]);return {deniedCode};}const recoveryId=randomUUID();const recovery=(await client.query<any>(`INSERT INTO workshopos.platform_log_recovery(recovery_id,log_id,requested_by,reason,status,restored_checksum_sha256,restored_until,verified_at) VALUES($1,$2,$3,$4,'VERIFIED',$5,transaction_timestamp()+interval '24 hours',transaction_timestamp()) RETURNING *`,[recoveryId,id,principal.identityId,reason,checksum])).rows[0];await client.query("INSERT INTO workshopos.platform_log_access_audit(audit_id,log_id,platform_actor_id,action,reason,outcome,trace_id) VALUES($1,$2,$3,'RECOVERY_EXERCISED',$4,'VERIFIED',$5)",[randomUUID(),id,principal.identityId,reason,traceId]);return {recovery:{id:recovery.recovery_id,status:recovery.status,restoredUntil:recovery.restored_until.toISOString(),checksumVerified:true}};});const denied="deniedCode" in result?result.deniedCode:undefined;if(denied)throw new ApiError(denied==="LOG_RETENTION_EXPIRED"?410:409,denied);return result;}
  async audit(principal:PlatformPrincipal){return this.inScope(principal,async client=>({logAccess:(await client.query<any>("SELECT audit_id id,log_id,platform_actor_id,action,reason,outcome,trace_id,occurred_at FROM workshopos.platform_log_access_audit ORDER BY occurred_at DESC LIMIT 100")).rows,emulatedActions:(await client.query<any>("SELECT action_id id,emulation_id,tenant_id,branch_id,platform_actor_id,effective_membership_id,method,route,phase,response_status,trace_id,occurred_at FROM workshopos.platform_emulated_action ORDER BY occurred_at DESC LIMIT 100")).rows}));}

  async close(){await this.pool.end();}
  private mapGrant=(row:any)=>({id:row.id,tenantId:row.tenant_id,supportIdentityId:row.support_identity_id,branchIds:row.branch_ids,permissions:row.permissions,reason:row.reason,status:row.status,requestedBy:row.requested_by,approvedBy:row.approved_by,approvalReason:row.approval_reason,version:Number(row.version),requestedAt:row.requested_at.toISOString(),approvedAt:row.approved_at?.toISOString(),expiresAt:row.expires_at.toISOString()});
  private mapEmulation(row:any){return{id:row.emulation_id,grantId:row.support_grant_id,tenantId:row.tenant_id,membershipId:row.effective_membership_id,branchId:row.branch_id,requestedBy:row.requested_by,approvedBy:row.approved_by,reason:row.reason,approvalReason:row.approval_reason,status:row.status,version:Number(row.version),requestedAt:row.requested_at.toISOString(),approvedAt:row.approved_at?.toISOString(),startedAt:row.started_at?.toISOString(),expiresAt:row.expires_at?.toISOString()};}
  private mapLog=(row:any)=>({id:row.id,date:row.log_date.toISOString().slice(0,10),objectKey:row.object_key,contentType:row.content_type,checksum:row.checksum_sha256,onlineUntil:row.online_until.toISOString(),recoverableUntil:row.recoverable_until.toISOString(),tier:row.tier,restored:row.restored});
  private async inScope<T>(principal:PlatformPrincipal,action:(client:PoolClient)=>Promise<T>):Promise<T>{const client=await this.pool.connect();try{await client.query("BEGIN");await client.query("SELECT set_config('app.platform_identity_id',$1,true),set_config('app.platform_permissions',$2,true),set_config('app.tenant_id','',true),set_config('app.branch_ids','',true)",[principal.identityId,principal.permissions.join(",")]);const result=await action(client);await client.query("COMMIT");return result;}catch(error){await client.query("ROLLBACK");throw error;}finally{client.release();}}
}
