import { ChevronLeft, ChevronRight, Plus } from "lucide-react";
import { useMemo, useState, type FormEvent } from "react";
import { createBooking, DEFAULT_GENERAL_CHECKUP_FOLLOWUP_BOOKING_CAPACITY, DEFAULT_SERVICE_WORK_BOOKING_CAPACITY, setBookingCapacityForDate } from "./db";
import type { Database } from "sql.js";
import type { Booking, BookingArrivalWindow, BookingServiceType, User, WorkshopState } from "./types";
import { Dialog } from "./ui-kit";
import { advanceBookingRange, clampAdvanceBookingDate, datesForCalendarMonth, isAdvanceBookingDate, shiftCalendarMonth } from "./advance-booking-range";

type Mutate = (action: (database: Database) => void, onError?: (message: string) => void) => boolean;
const windows: BookingArrivalWindow[] = ["", "Morning", "Afternoon", "Evening"];
const serviceTypes: BookingServiceType[] = ["Service Work", "General Checkup / Follow-up"];
const active = new Set<Booking["status"]>(["Booked", "Confirmed", "Rescheduled"]);
const quotaKey = (type: BookingServiceType) => type === "Service Work" ? "serviceWork" : "generalCheckupFollowup";
function dateLabel(date: string) { return new Date(`${date}T00:00:00`).toLocaleDateString("en-IN", { weekday: "long", day: "numeric", month: "long", year: "numeric" }); }
function monthLabel(month: string) { return new Date(`${month}-01T00:00:00`).toLocaleDateString("en-IN", { month: "long", year: "numeric" }); }
function capacityFor(state: WorkshopState, bookingDate: string) {
  const configured = state.booking_capacity_limits.find((row) => row.booking_date === bookingDate);
  const quota = (serviceType: BookingServiceType) => {
    const limit = serviceType === "Service Work" ? configured?.service_work_capacity ?? DEFAULT_SERVICE_WORK_BOOKING_CAPACITY : configured?.general_checkup_followup_capacity ?? DEFAULT_GENERAL_CHECKUP_FOLLOWUP_BOOKING_CAPACITY;
    const count = state.bookings.filter((b) => b.booking_date === bookingDate && b.service_type === serviceType && active.has(b.status)).length;
    return { limit, count, remaining: Math.max(0, limit - count) };
  };
  return { serviceWork: quota("Service Work"), generalCheckupFollowup: quota("General Checkup / Follow-up") };
}
type BookingDraft = { customerName: string; mobile: string; customerType: string; vehicleNo: string; make: string; model: string; color: string; requestedWork: string; serviceType: BookingServiceType; bookingDate: string; arrivalWindow: BookingArrivalWindow; capacityOverrideReason: string; };
const draftFor = (bookingDate: string): BookingDraft => ({ customerName: "", mobile: "", customerType: "Individual", vehicleNo: "", make: "", model: "", color: "", requestedWork: "", serviceType: "Service Work", bookingDate, arrivalWindow: "", capacityOverrideReason: "" });

export function BookingCalendar({ state, actor, mutate }: { state: WorkshopState; actor: User; mutate: Mutate }) {
  const range = useMemo(() => advanceBookingRange(), []); const [month, setMonth] = useState(range.firstMonth); const [selectedDate, setSelectedDate] = useState(range.min); const [creating, setCreating] = useState(false); const [editingCapacity, setEditingCapacity] = useState(false); const [form, setForm] = useState<BookingDraft>(() => draftFor(range.min)); const [error, setError] = useState("");
  const draftCapacity = (date: string) => { const c = capacityFor(state, date); return { serviceWork: String(c.serviceWork.limit), generalCheckupFollowup: String(c.generalCheckupFollowup.limit) }; };
  const [capacityDraft, setCapacityDraft] = useState(() => draftCapacity(range.min)); const capacity = capacityFor(state, selectedDate); const canOverride = actor.role === "admin";
  const quota = (date: string, type: BookingServiceType) => capacityFor(state, date)[quotaKey(type)]; const formQuota = quota(form.bookingDate, form.serviceType);
  const bookings = useMemo(() => state.bookings.filter((b) => b.booking_date === selectedDate).sort((a, b) => a.created_at.localeCompare(b.created_at)), [state.bookings, selectedDate]);
  const overrides = useMemo(() => new Map(state.booking_capacity_overrides.filter((r) => r.booking_date === selectedDate).map((r) => [r.booking_id, r])), [state.booking_capacity_overrides, selectedDate]);
  const selectDate = (date: string) => { setSelectedDate(date); setCapacityDraft(draftCapacity(date)); };
  const changeMonth = (delta: -1 | 1) => { const next = shiftCalendarMonth(month, delta); if (next < range.firstMonth || next > range.lastMonth) return; setMonth(next); selectDate(clampAdvanceBookingDate(`${next}-01`, range)); };
  const submit = (event: FormEvent) => { event.preventDefault(); if (mutate((db) => createBooking(db, actor.id, form), setError)) setCreating(false); };
  const saveLimits = (event: FormEvent) => { event.preventDefault(); if (mutate((db) => setBookingCapacityForDate(db, actor.id, selectedDate, { serviceWork: Number(capacityDraft.serviceWork), generalCheckupFollowup: Number(capacityDraft.generalCheckupFollowup) }), setError)) setEditingCapacity(false); };
  return <section className="workspace booking-calendar-workspace" aria-label="Advance booking calendar"><div className="desk-panel">
    <div className="panel-actions"><div><h2>Advance Bookings</h2><p>Plan customer arrivals by date. Advisor assignment happens only after check-in.</p></div><button className="primary-action" onClick={() => { setForm(draftFor(selectedDate)); setError(""); setCreating(true); }} disabled={!canOverride && !capacity.serviceWork.remaining && !capacity.generalCheckupFollowup.remaining}><Plus size={16} /> Create Booking</button></div>
    <div className="booking-calendar-layout"><section className="booking-month-panel" aria-label="Booking month calendar"><div className="booking-month-toolbar"><button type="button" aria-label="Previous month" disabled={month === range.firstMonth} onClick={() => changeMonth(-1)}><ChevronLeft size={18} /></button><h3>{monthLabel(month)}</h3><button type="button" aria-label="Next month" disabled={month === range.lastMonth} onClick={() => changeMonth(1)}><ChevronRight size={18} /></button></div><div className="booking-calendar-grid" role="grid" aria-label={`${monthLabel(month)} bookings`}>{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((d) => <strong key={d} role="columnheader">{d}</strong>)}{datesForCalendarMonth(month).map((date) => { const c = capacityFor(state, date); const full = !c.serviceWork.remaining && !c.generalCheckupFollowup.remaining; return <button type="button" key={date} role="gridcell" disabled={!isAdvanceBookingDate(date, range)} onClick={() => selectDate(date)} className={`booking-calendar-day${!date.startsWith(month) ? " outside-month" : ""}${date === selectedDate ? " selected" : ""}${full ? " full" : ""}`} aria-pressed={date === selectedDate}><span>{Number(date.slice(-2))}</span><small>SW {c.serviceWork.count}/{c.serviceWork.limit} · C {c.generalCheckupFollowup.count}/{c.generalCheckupFollowup.limit}</small></button>; })}</div><p className="booking-calendar-legend"><span className="calendar-full-dot" /> SW = Service Work · C = General Checkup / Follow-up.</p></section>
      <section className="booking-day-detail" aria-live="polite"><div className="panel-actions"><div><h3>{dateLabel(selectedDate)}</h3><p>Service Work: <strong>{capacity.serviceWork.count}/{capacity.serviceWork.limit}</strong> · {capacity.serviceWork.remaining} remaining</p><p>General Checkup / Follow-up: <strong>{capacity.generalCheckupFollowup.count}/{capacity.generalCheckupFollowup.limit}</strong> · {capacity.generalCheckupFollowup.remaining} remaining</p></div>{canOverride && <button type="button" aria-label="Admin control: set daily booking limits" onClick={() => { setCapacityDraft(draftCapacity(selectedDate)); setError(""); setEditingCapacity(true); }}>Admin: Set limits</button>}</div>{(!capacity.serviceWork.remaining || !capacity.generalCheckupFollowup.remaining) && <p className="booking-capacity-alert" role="status">{!capacity.serviceWork.remaining ? "Service Work is full. " : ""}{!capacity.generalCheckupFollowup.remaining ? "General Checkup / Follow-up is full. " : ""}Reception cannot select a full type.{canOverride ? " Admin may add one with an override reason." : ""}</p>}<div className="booking-day-list">{bookings.length === 0 ? <p className="empty-state">No advance bookings for this day.</p> : bookings.map((b) => <article className="booking-day-row" key={b.id}><div><strong>{b.customer_name}</strong><span>{b.vehicle_no} · {b.make} {b.model}</span><span>{b.service_type} · {b.arrival_window || "Arrival window not set"} · {b.status}</span></div><div><span>{b.mobile}</span>{overrides.get(b.id) && <small>Admin override: {overrides.get(b.id)!.reason}</small>}</div></article>)}</div></section></div></div>
    {creating && <Dialog title="Create advance booking" subtitle={`Booking for ${dateLabel(selectedDate)}`} onClose={() => setCreating(false)}><form className="booking-form" onSubmit={submit}><label>Customer name<input required value={form.customerName} onChange={(e) => setForm({ ...form, customerName: e.target.value })} /></label><label>Mobile<input required value={form.mobile} onChange={(e) => setForm({ ...form, mobile: e.target.value })} /></label><label>Vehicle number<input required value={form.vehicleNo} onChange={(e) => setForm({ ...form, vehicleNo: e.target.value.toUpperCase() })} /></label><label>Make<input required value={form.make} onChange={(e) => setForm({ ...form, make: e.target.value })} /></label><label>Model<input required value={form.model} onChange={(e) => setForm({ ...form, model: e.target.value })} /></label><label>Color<input value={form.color} onChange={(e) => setForm({ ...form, color: e.target.value })} /></label><label>Booking date<input required type="date" min={range.min} max={range.max} value={form.bookingDate} onChange={(e) => setForm({ ...form, bookingDate: e.target.value })} /></label><label>Service type<select required value={form.serviceType} onChange={(e) => setForm({ ...form, serviceType: e.target.value as BookingServiceType })}>{serviceTypes.map((type) => <option key={type} value={type} disabled={!canOverride && quota(form.bookingDate, type).remaining === 0}>{type}{quota(form.bookingDate, type).remaining === 0 ? " (full)" : ""}</option>)}</select></label><label>Arrival window<select value={form.arrivalWindow} onChange={(e) => setForm({ ...form, arrivalWindow: e.target.value as BookingArrivalWindow })}>{windows.map((w) => <option key={w} value={w}>{w || "Not set"}</option>)}</select></label><label className="booking-form-wide">Requested work<textarea required value={form.requestedWork} onChange={(e) => setForm({ ...form, requestedWork: e.target.value })} /></label>{formQuota.remaining === 0 && canOverride && <label className="booking-form-wide">Admin override reason (recorded in the booking audit trail)<textarea required value={form.capacityOverrideReason} onChange={(e) => setForm({ ...form, capacityOverrideReason: e.target.value })} /></label>}{error && <p className="error-text booking-form-wide" role="alert">{error}</p>}<div className="action-row booking-form-wide"><button className="primary-action">Save Booking</button><button type="button" onClick={() => setCreating(false)}>Cancel</button></div></form></Dialog>}
    {editingCapacity && <Dialog title="Set daily booking limits" subtitle={dateLabel(selectedDate)} onClose={() => setEditingCapacity(false)}><form onSubmit={saveLimits}><label>Service Work bookings allowed<input aria-label="Service Work booking capacity" required type="number" min="0" step="1" value={capacityDraft.serviceWork} onChange={(e) => setCapacityDraft({ ...capacityDraft, serviceWork: e.target.value })} /></label><label>General Checkup / Follow-up bookings allowed<input aria-label="General Checkup / Follow-up booking capacity" required type="number" min="0" step="1" value={capacityDraft.generalCheckupFollowup} onChange={(e) => setCapacityDraft({ ...capacityDraft, generalCheckupFollowup: e.target.value })} /></label>{error && <p className="error-text" role="alert">{error}</p>}<div className="action-row"><button className="primary-action">Save limits</button><button type="button" onClick={() => setEditingCapacity(false)}>Cancel</button></div></form></Dialog>}
  </section>;
}
