import { useState, type FormEvent } from "react";
import { Building2, Mail, MessageCircle, Play, Plus, RotateCcw, ShieldCheck } from "lucide-react";
import { chargeStatus, createPlatformCharge, createTenant, EMULATION_ROLE_LABELS, recordPlatformPayment, selectedTenant, setTenantLifecycle, simulateCommunicationTest, updateCommunication, updateTenantProfile, type DeveloperControlPlaneState, type EmulationRole, type TenantProfile } from "./developer-control-plane";

export function DeveloperConsole({ state, commit, onEmulate, onReset }: { state: DeveloperControlPlaneState; commit: (action: (current: DeveloperControlPlaneState) => DeveloperControlPlaneState) => void; onEmulate: (role: EmulationRole) => void; onReset: () => void; }) {
  const tenant = selectedTenant(state);
  const [tab, setTab] = useState<"Tenants" | "Communications" | "Billing">("Tenants");
  const [role, setRole] = useState<EmulationRole>("admin");
  const [notice, setNotice] = useState("");
  const test = (channel: "email" | "whatsapp") => { commit((current) => simulateCommunicationTest(current, channel, tenant.id, tenant.profile.email)); setNotice(`${channel === "email" ? "Email" : "WhatsApp"} test queued as a simulated delivery.`); };
  return <main className="developer-console">
    <header className="developer-header"><div><p>Developer control plane · browser demo only</p><h1><ShieldCheck size={28} /> Developer Console</h1></div><button className="danger-action" onClick={onReset}><RotateCcw size={16} /> Reset demo</button></header>
    <div className="management-tabs" role="tablist" aria-label="Developer Console tabs">{(["Tenants", "Communications", "Billing"] as const).map((item) => <button key={item} role="tab" aria-selected={tab === item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>
    {notice && <p className="success-text">{notice}</p>}
    {tab === "Tenants" && <section className="developer-grid"><div className="desk-panel"><h2>Demo tenants</h2>{state.tenants.map((item) => <button className={`tenant-row ${item.id === tenant.id ? "selected" : ""}`} key={item.id} onClick={() => commit((current) => ({ ...current, selectedTenantId: item.id }))}><Building2 size={18}/><span><strong>{item.profile.name}</strong><small>{item.lifecycle}</small></span></button>)}<TenantCreate onCreate={(profile) => commit((current) => createTenant(current, profile))}/></div><div className="desk-panel"><h2>{tenant.profile.name}</h2><TenantProfileForm profile={tenant.profile} onSave={(profile) => commit((current) => updateTenantProfile(current, tenant.id, profile))}/><div className="developer-actions"><button className={tenant.lifecycle === "active" ? "danger-action" : "primary-action"} onClick={() => commit((current) => setTenantLifecycle(current, tenant.id, tenant.lifecycle === "active" ? "disabled" : "active"))}>{tenant.lifecycle === "active" ? "Disable tenant" : "Restore tenant"}</button><select aria-label="Emulate role" value={role} onChange={(event) => setRole(event.target.value as EmulationRole)}>{Object.entries(EMULATION_ROLE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button className="primary-action" disabled={tenant.lifecycle !== "active"} onClick={() => onEmulate(role)}><Play size={16}/> Emulate tenant</button></div>{tenant.lifecycle !== "active" && <p className="error-text">Disabled tenants cannot be emulated or used operationally.</p>}</div></section>}
    {tab === "Communications" && <section className="developer-grid">{(["email", "whatsapp"] as const).map((channel) => <div className="desk-panel" key={channel}><h2>{channel === "email" ? <Mail size={20}/> : <MessageCircle size={20}/>} {channel === "email" ? "Email" : "WhatsApp"}</h2><label className="switch-line"><input type="checkbox" checked={state.communications[channel].active} onChange={(event) => commit((current) => updateCommunication(current, channel, { active: event.target.checked }))}/> Channel active</label><label>Default sender<input value={state.communications[channel].sender} onChange={(event) => commit((current) => updateCommunication(current, channel, { sender: event.target.value }))}/></label><button className="primary-action" onClick={() => test(channel)}>Send simulated test</button></div>)}</section>}
    {tab === "Communications" && <section className="desk-panel"><h2>Simulated delivery log</h2>{state.communicationLogs.length ? <ul className="developer-log">{state.communicationLogs.map((item) => <li key={item.id}>{item.channel} to {item.recipient} — <strong>{item.result}</strong></li>)}</ul> : <p>No test sends yet.</p>}</section>}
    {tab === "Billing" && <Billing state={state} tenantId={tenant.id} commit={commit}/>}</main>;
}

function TenantCreate({ onCreate }: { onCreate: (profile: TenantProfile) => void }) { const [name, setName] = useState(""); const submit = (event: FormEvent) => { event.preventDefault(); if (!name.trim()) return; onCreate({ name, brandName: name, address: "", contactName: "", email: "", phone: "", gstin: "", timezone: "Asia/Kolkata", currency: "INR", invoicePrefix: name.slice(0, 4).toUpperCase() }); setName(""); }; return <form className="inline-form" onSubmit={submit}><input aria-label="New tenant name" value={name} onChange={(event) => setName(event.target.value)} placeholder="New workshop name"/><button className="primary-action"><Plus size={16}/> Create tenant</button></form>; }
function TenantProfileForm({ profile, onSave }: { profile: TenantProfile; onSave: (profile: Partial<TenantProfile>) => void }) { const [draft, setDraft] = useState(profile); const change = (key: keyof TenantProfile, value: string) => setDraft({ ...draft, [key]: value }); return <form className="developer-form" onSubmit={(event) => { event.preventDefault(); onSave(draft); }}><div className="developer-form-grid">{(["name", "brandName", "address", "contactName", "email", "phone", "gstin", "timezone", "currency", "invoicePrefix"] as const).map((key) => <label key={key}>{key.replace(/([A-Z])/g, " $1")}<input value={draft[key]} onChange={(event) => change(key, event.target.value)}/></label>)}</div><button className="primary-action">Save company profile</button></form>; }
function Billing({ state, tenantId, commit }: { state: DeveloperControlPlaneState; tenantId: string; commit: (action: (current: DeveloperControlPlaneState) => DeveloperControlPlaneState) => void }) { const [description, setDescription] = useState(""); const [amount, setAmount] = useState(""); const [dueDate, setDueDate] = useState(""); const [payment, setPayment] = useState<Record<string, string>>({}); const charges = state.charges.filter((charge) => charge.tenantId === tenantId); return <section className="developer-grid billing-grid"><form className="desk-panel developer-form" onSubmit={(event) => { event.preventDefault(); commit((current) => createPlatformCharge(current, { tenantId, description, amount: Number(amount), dueDate })); setDescription(""); setAmount(""); setDueDate(""); }}><h2>Quick platform charge</h2><label>Description<input value={description} onChange={(event) => setDescription(event.target.value)}/></label><label>Amount<input type="number" min="1" value={amount} onChange={(event) => setAmount(event.target.value)}/></label><label>Due date<input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)}/></label><button className="primary-action">Create charge</button></form><div className="desk-panel"><h2>Charges</h2>{charges.length ? charges.map((charge) => { const paid = charge.payments.reduce((sum, item) => sum + item.amount, 0); return <article className="charge-row" key={charge.id}><strong>{charge.description}</strong><span>₹{charge.amount} · {chargeStatus(charge)} · due {charge.dueDate}</span><small>Paid ₹{paid}; {charge.payments.length} payment(s)</small><div><input aria-label={`Payment for ${charge.description}`} type="number" min="1" placeholder="Payment amount" value={payment[charge.id] ?? ""} onChange={(event) => setPayment({ ...payment, [charge.id]: event.target.value })}/><button onClick={() => { const value = Number(payment[charge.id]); if (value > 0) { commit((current) => recordPlatformPayment(current, charge.id, value)); setPayment({ ...payment, [charge.id]: "" }); } }}>Record payment</button></div></article>; }) : <p>No charges for this tenant.</p>}</div></section>; }
