import { useEffect, useMemo, useState } from "react";
import { normalizeSearch } from "./list-utils";
import type { JobView } from "./types";

export type JobPeriod = { date: string; month: string; year: string };
export function localCalendarDate(now = new Date()) { const offset = now.getTimezoneOffset() * 60_000; return new Date(now.getTime() - offset).toISOString().slice(0, 10); }
export function todayJobPeriod(now = new Date()): JobPeriod { return { date: localCalendarDate(now), month: String(now.getMonth() + 1).padStart(2, "0"), year: String(now.getFullYear()) }; }
export function jobMatchesPeriod(view: JobView, period: JobPeriod) { const received = view.visit.received_at.slice(0, 10); return period.date ? received === period.date : (period.month === "ALL" || received.slice(5, 7) === period.month) && (period.year === "ALL" || received.slice(0, 4) === period.year); }
export function jobsForPeriod(jobs: JobView[], period: JobPeriod) { return jobs.filter((view) => jobMatchesPeriod(view, period)); }
export function selectedJobRemainsInPeriod(jobs: JobView[], selectedJobId: number | undefined, period: JobPeriod) { return !selectedJobId || jobsForPeriod(jobs, period).some((view) => view.job.id === selectedJobId); }

const months = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
export function JobPicker({ jobs, selectedJobId, onSelect, label = "Select job", period: controlledPeriod, onPeriodChange, onClear, showJobResults = true }: { jobs: JobView[]; selectedJobId?: number; onSelect: (id?: number) => void; label?: string; period?: JobPeriod; onPeriodChange?: (period: JobPeriod) => void; onClear?: () => void; showJobResults?: boolean }) {
  const [localPeriod, setLocalPeriod] = useState(todayJobPeriod); const [query, setQuery] = useState(""); const period = controlledPeriod ?? localPeriod;
  const setPeriod = (next: JobPeriod) => { if (!selectedJobRemainsInPeriod(jobs, selectedJobId, next)) onSelect(undefined); if (controlledPeriod) onPeriodChange?.(next); else setLocalPeriod(next); };
  const reset = () => { const next = todayJobPeriod(); setQuery(""); onSelect(undefined); if (controlledPeriod) onPeriodChange?.(next); else setLocalPeriod(next); onClear?.(); };
  const periodJobs = useMemo(() => jobsForPeriod(jobs, period), [jobs, period]); const needle = normalizeSearch(query);
  const options = periodJobs.filter((view) => !needle || normalizeSearch(`${view.job.job_no} ${view.vehicle.number} ${view.customer.name} ${view.customer.mobile}`).includes(needle));
  const years = useMemo(() => [...new Set(jobs.map((view) => view.visit.received_at.slice(0, 4)).filter(Boolean))].sort().reverse(), [jobs]);
  useEffect(() => { if (!selectedJobRemainsInPeriod(jobs, selectedJobId, period)) onSelect(undefined); }, [jobs, period, selectedJobId, onSelect]);
  return <div className="job-selector">{showJobResults && <label>{label}<input type="search" aria-label={`${label} search`} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Job, vehicle, customer or mobile" /></label>}<label>Received date<input type="date" aria-label={`${label} received date`} value={period.date} onChange={(event) => setPeriod({ ...period, date: event.target.value })} /></label><label>Month<select aria-label={`${label} month`} value={period.month} onChange={(event) => setPeriod({ ...period, date: "", month: event.target.value })}><option value="ALL">All months</option>{months.map((name, index) => <option key={name} value={String(index + 1).padStart(2, "0")}>{name}</option>)}</select></label><label>Year<select aria-label={`${label} year`} value={period.year} onChange={(event) => setPeriod({ ...period, date: "", year: event.target.value })}><option value="ALL">All years</option>{years.map((year) => <option key={year} value={year}>{year}</option>)}</select></label>{showJobResults && <label>Matching jobs<select aria-label="Job results" value={selectedJobId ?? ""} onChange={(event) => onSelect(event.target.value ? Number(event.target.value) : undefined)}><option value="">Choose a job</option>{options.map((view) => <option key={view.job.id} value={view.job.id}>{view.job.job_no} · {view.vehicle.number} · {view.customer.name}</option>)}</select></label>}<button type="button" className="compact-action" onClick={reset}>Clear filters</button>{showJobResults && query && options.length === 0 && <p className="job-picker-empty" role="status">No matching jobs</p>}</div>;
}
