import { useMemo, useState, type FormEvent } from "react";
import { createSalesLead, createSalesQuotation, setSalesQuotationStatus, updateSalesLead } from "./db";
import { loadAdminDemoState } from "./admin-demo-state";
import { SalesLeadDialog, blankLeadDraft, type LeadFormDraft } from "./sales-lead-dialog";
import type { SalesLead, WorkshopState } from "./types";
import type { Mutate } from "./App";

const leadDraft = (lead: SalesLead): LeadFormDraft => ({ displayName: lead.display_name, phone: lead.phone, company: lead.company, email: lead.email, address: lead.address, serviceInterest: lead.service_interest, notes: lead.notes, stage: lead.stage, temperature: lead.temperature, followUpDue: lead.follow_up_due, siteVisitCompleted: Boolean(lead.site_visit_completed), siteVisitDate: lead.site_visit_date });
const localLeadInput = (lead: LeadFormDraft) => ({ display_name: lead.displayName, phone: lead.phone, company: lead.company, email: lead.email, address: lead.address, service_interest: lead.serviceInterest, notes: lead.notes, stage: lead.stage, temperature: lead.temperature, follow_up_due: lead.followUpDue, site_visit_completed: Number(lead.siteVisitCompleted), site_visit_date: lead.siteVisitDate });

export function LocalSalesWorkspace({ mode, state, mutate }: { mode: "leads" | "quotations"; state: WorkshopState; mutate: Mutate }) {
  const [query, setQuery] = useState(""); const [leadDialog, setLeadDialog] = useState<"add" | "edit" | null>(null); const [selectedLead, setSelectedLead] = useState<SalesLead | null>(null); const [showQuotation, setShowQuotation] = useState(false); const [leadId, setLeadId] = useState(0); const [templateId, setTemplateId] = useState(""); const [description, setDescription] = useState(""); const [rate, setRate] = useState(""); const [discount, setDiscount] = useState("0"); const [lines, setLines] = useState<Array<{ kind: string; description: string; quantity: number; rate: number; gst_rate: number }>>([]);
  const templates = useMemo(() => loadAdminDemoState().reportTemplates.filter((template) => template.category === "quotation"), []);
  const filteredLeads = state.sales_leads.filter((item) => `${item.display_name} ${item.company} ${item.phone}`.toLowerCase().includes(query.toLowerCase()));
  const filteredQuotations = state.sales_quotations.filter((item) => `${item.quotation_no} ${state.sales_leads.find((lead) => lead.id === item.lead_id)?.display_name ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  const closeLeadDialog = () => { setLeadDialog(null); setSelectedLead(null); };
  const saveLead = (draft: LeadFormDraft) => { const input = localLeadInput(draft); const ok = leadDialog === "edit" && selectedLead ? mutate((db) => updateSalesLead(db, selectedLead.id, input)) : mutate((db) => createSalesLead(db, input)); if (ok) closeLeadDialog(); };
  const addLine = () => { if (description.trim()) { setLines((current) => [...current, { kind: "Service", description: description.trim(), quantity: 1, rate: Number(rate) || 0, gst_rate: 18 }]); setDescription(""); setRate(""); } };
  const saveQuotation = (event: FormEvent) => { event.preventDefault(); const template = templates.find((item) => item.id === templateId); if (!template) return; if (mutate((db) => createSalesQuotation(db, { lead_id: leadId, template_id: template.id, template_html: template.html, discount: Number(discount) || 0, lines }))) { setShowQuotation(false); setLines([]); setLeadId(0); } };
  if (mode === "leads") return <section className="workspace single-panel"><div className="desk-panel"><div className="panel-actions"><div><h2>Sales Leads</h2><p>Local CRM inquiries, follow-ups, and site visits.</p></div><button className="primary-action" onClick={() => { setSelectedLead(null); setLeadDialog("add"); }}>New Lead</button></div><label className="list-search">Search leads<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Name, company, or phone" /></label>{leadDialog && <SalesLeadDialog lead={selectedLead ? leadDraft(selectedLead) : blankLeadDraft} editing={leadDialog === "edit"} onSave={saveLead} onClose={closeLeadDialog} />}<SalesLeadTable leads={filteredLeads} onEdit={(lead) => { setSelectedLead(lead); setLeadDialog("edit"); }} /></div></section>;
  return <section className="workspace single-panel"><div className="desk-panel"><div className="panel-actions"><div><h2>Quotations</h2><p>Local, frozen quotation documents and lifecycle.</p></div><button className="primary-action" onClick={() => { setTemplateId(templates.find((item) => item.active)?.id ?? templates[0]?.id ?? ""); setShowQuotation(true); }}>New Quotation</button></div><label className="list-search">Search quotations<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Quotation number or lead" /></label>{showQuotation && <form className="form-grid" onSubmit={saveQuotation}><h3>Create quotation</h3><label>Lead<select required value={leadId} onChange={(event) => setLeadId(Number(event.target.value))}><option value={0}>Select lead</option>{state.sales_leads.map((item) => <option key={item.id} value={item.id}>{item.display_name} · {item.phone}</option>)}</select></label><label>Template<select required value={templateId} onChange={(event) => setTemplateId(event.target.value)}>{templates.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Discount<input type="number" min="0" value={discount} onChange={(event) => setDiscount(event.target.value)} /></label><label>Line description<input value={description} onChange={(event) => setDescription(event.target.value)} /></label><label>Base rate<input type="number" min="0" value={rate} onChange={(event) => setRate(event.target.value)} /></label><button type="button" onClick={addLine}>Add line</button>{lines.map((line, index) => <p key={`${line.description}-${index}`}>{line.description} · ₹{line.rate.toFixed(2)} <button type="button" onClick={() => setLines((current) => current.filter((_, lineIndex) => lineIndex !== index))}>Remove</button></p>)}<div className="action-row"><button className="primary-action" disabled={!leadId || !lines.length}>Create quotation</button><button type="button" onClick={() => setShowQuotation(false)}>Cancel</button></div></form>}<div className="table-wrap"><table aria-label="Quotation register"><thead><tr><th>Number</th><th>Lead</th><th>Status</th><th>Amount</th><th>Actions</th></tr></thead><tbody>{filteredQuotations.map((item) => <tr key={item.id}><td>{item.quotation_no}</td><td>{state.sales_leads.find((lead) => lead.id === item.lead_id)?.display_name ?? item.lead_id}</td><td>{item.status}</td><td>₹{item.total.toFixed(2)}</td><td><button disabled={["ACCEPTED", "REJECTED", "EXPIRED"].includes(item.status)} onClick={() => mutate((db) => setSalesQuotationStatus(db, item.id, "SENT"))}>Mark sent</button> <button disabled={item.status !== "SENT"} onClick={() => mutate((db) => setSalesQuotationStatus(db, item.id, "ACCEPTED"))}>Accept</button></td></tr>)}</tbody></table></div>{!filteredQuotations.length && <p className="empty-state">No quotations match these filters.</p>}</div></section>;
}

function SalesLeadTable({ leads, onEdit }: { leads: SalesLead[]; onEdit: (lead: SalesLead) => void }) { return <div className="table-wrap"><table aria-label="Sales leads"><thead><tr><th>Lead</th><th>Contact</th><th>Stage</th><th>Temperature</th><th>Follow-up</th><th>Actions</th></tr></thead><tbody>{leads.map((item) => <tr key={item.id}><td><strong>{item.display_name}</strong><br />{item.company || "—"}</td><td>{item.phone}<br />{item.email || "—"}</td><td>{item.stage.replaceAll("_", " ")}</td><td>{item.temperature}</td><td>{item.follow_up_due || "—"}</td><td><button onClick={() => onEdit(item)}>Edit</button></td></tr>)}</tbody></table>{!leads.length && <p className="empty-state">No leads match these filters.</p>}</div>; }
