import { useEffect, useId, useRef, useState } from "react";
import type { Database } from "sql.js";
import { addMaterialRowForActor, cancelMaterialRowForActor, createMaterialPurchaseRequestForActor, deleteMaterialRowForActor, editIssuedMaterialRowForActor, reRequestMaterialRowForActor, requestMaterialRowForActor, updateMaterialRowForActor } from "./db";
import { canManageMaterialRows, filterInventory, materialRowActionsFor, materialRowStatus, overStockWarning, pickerLabel } from "./materials";
import type { InventoryItem, JobView, MaterialPurchaseRequest, MaterialRequest, User } from "./types";
import type { Mutate } from "./App";
import { usePickerDismissal } from "./ui-kit";

export function InventoryPicker({ inventory, value, onChange, label, disabled = false, allOptionLabel, onSelectAll }: { inventory: InventoryItem[]; value?: number; onChange: (id: number) => void; label: string; disabled?: boolean; allOptionLabel?: string; onSelectAll?: () => void }) {
  const selected = inventory.find((item) => item.id === value);
  const [query, setQuery] = useState(selected?.name ?? ""); const [open, setOpen] = useState(false); const [activeIndex, setActiveIndex] = useState(0); const listId = useId();
  const rootRef = useRef<HTMLDivElement>(null);
  usePickerDismissal(rootRef, open, () => setOpen(false));
  const allSelected = Boolean(allOptionLabel && value === undefined);
  const matches = filterInventory(inventory, (selected && query === selected.name) || (allSelected && query === allOptionLabel) ? "" : query).slice(0, 8);
  const options: Array<InventoryItem | undefined> = allOptionLabel ? [undefined, ...matches] : matches;
  useEffect(() => { setQuery(allSelected ? allOptionLabel! : selected?.name ?? ""); }, [allOptionLabel, allSelected, selected?.id]);
  const choose = (item: InventoryItem) => { onChange(item.id); setQuery(item.name); setOpen(false); };
  const chooseOption = (option: InventoryItem | undefined) => { if (option) choose(option); else if (onSelectAll) { onSelectAll(); setQuery(allOptionLabel ?? ""); setOpen(false); } };
  return <div className="inventory-picker" ref={rootRef}><input aria-label={label} role="combobox" aria-expanded={open} aria-controls={listId} aria-activedescendant={open && options[activeIndex] ? `${listId}-${options[activeIndex]!.id}` : open && allOptionLabel ? `${listId}-all` : undefined} aria-autocomplete="list" disabled={disabled} value={query} placeholder="Type to search inventory" onFocus={() => { setOpen(true); setActiveIndex(0); }} onChange={(event) => { setQuery(event.target.value); setOpen(true); setActiveIndex(0); }} onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); setOpen(true); setActiveIndex((index) => Math.min(index + 1, Math.max(options.length - 1, 0))); } else if (event.key === "ArrowUp") { event.preventDefault(); setOpen(true); setActiveIndex((index) => Math.max(index - 1, 0)); } else if (event.key === "Enter" && open && options[activeIndex] !== undefined) { event.preventDefault(); chooseOption(options[activeIndex]); } else if (event.key === "Enter" && open && allOptionLabel && activeIndex === 0) { event.preventDefault(); chooseOption(undefined); } else if (event.key === "Escape") setOpen(false); }} />
    {open && <ul id={listId} role="listbox" aria-label={`${label} options`} className="inventory-picker-options">{options.map((option, index) => <li id={option ? `${listId}-${option.id}` : `${listId}-all`} key={option?.id ?? "all"} role="option" aria-selected={index === activeIndex}><button type="button" onMouseDown={(event) => event.preventDefault()} onClick={() => chooseOption(option)}>{option ? pickerLabel(option) : allOptionLabel}</button></li>)}{matches.length === 0 && !allOptionLabel && <li className="empty-state">No matching inventory</li>}</ul>}
    {selected && <small className="picker-stock">in stock: {selected.stock_qty} {selected.unit}</small>}</div>;
}

function MaterialRow({ row, job, inventory, actor, mutate }: { row: MaterialRequest; job: JobView["job"] & { materialApprovalStatus?: "Pending" | "Approved" | "Rejected" }; inventory: InventoryItem[]; actor: User; mutate: Mutate }) {
  const item = inventory.find((candidate) => candidate.id === row.item_id); const actions = canManageMaterialRows(actor, job) ? materialRowActionsFor(actor, job, row) : [];
  const [editing, setEditing] = useState(false); const [itemId, setItemId] = useState(row.item_id); const [qty, setQty] = useState(row.requested_qty); const [note, setNote] = useState(""); const [error, setError] = useState("");
  const run = (action: (db: Database) => unknown) => mutate((db) => action(db), setError); const status = materialRowStatus(row); const issued = actions.includes("edit-issued"); const draft = actions.includes("edit"); const warning = overStockWarning(editing ? qty : row.requested_qty, (editing ? inventory.find((candidate) => candidate.id === itemId) : item)?.stock_qty ?? 0);
  return <tr><td>{editing ? <InventoryPicker inventory={inventory} value={itemId} onChange={setItemId} label="Item" /> : item?.name ?? `Item ${row.item_id}`}</td><td>{editing ? <input aria-label="Qty" type="number" min="0.01" step="0.01" value={qty} onChange={(event) => setQty(Number(event.target.value))} /> : `${row.requested_qty} ${item?.unit ?? ""}`}</td><td><span className={`status-badge material-status material-status-${status.toLowerCase()}`}>{status}</span>{warning && <p className="permission-note" role="status">{warning}</p>}{error && <p className="error-text" role="alert">{error}</p>}</td><td><div className="grid-actions material-table-actions">{editing ? <>{issued && <input aria-label="Edit request note" placeholder="Note required" value={note} onChange={(event) => setNote(event.target.value)} />}<button type="button" className="grid-action" onClick={() => { const ok = run((db) => issued ? editIssuedMaterialRowForActor(db, row.id, actor.id, itemId, qty, note) : draft ? updateMaterialRowForActor(db, row.id, actor.id, itemId, qty) : reRequestMaterialRowForActor(db, row.id, actor.id, itemId, qty)); if (ok) setEditing(false); }}>Save</button><button type="button" className="grid-action" onClick={() => setEditing(false)}>Cancel</button></> : <>{actions.includes("request") && <button type="button" className="grid-action" onClick={() => run((db) => requestMaterialRowForActor(db, row.id, actor.id))}>Request Item</button>}{(actions.includes("edit") || actions.includes("re-request") || issued) && <button type="button" className="grid-action" onClick={() => setEditing(true)}>Edit Request</button>}{actions.includes("cancel") && <button type="button" className="grid-action grid-action-danger" onClick={() => run((db) => cancelMaterialRowForActor(db, row.id, actor.id))}>Cancel Request</button>}{actions.includes("delete") && <button type="button" className="grid-action grid-action-danger" onClick={() => run((db) => deleteMaterialRowForActor(db, row.id, actor.id))}>Delete</button>}</>}</div></td></tr>;
}

function PurchaseRequestTable({ rows, inventory }: { rows: MaterialPurchaseRequest[]; inventory: InventoryItem[] }) {
  if (!rows.length) return null;
  return <section className="material-purchase-requests" aria-label="New item purchase requests"><h4>New item purchase requests</h4><div className="material-table-scroll"><table><thead><tr><th>Item</th><th>Qty</th><th>Status</th><th>Resolution</th></tr></thead><tbody>{rows.map((row) => { const item = inventory.find((candidate) => candidate.id === row.mapped_inventory_item_id); return <tr key={row.id}><td>{row.item_name}</td><td>{row.quantity} {row.unit}</td><td>{row.status}</td><td>{row.status === "Completed" ? `${item?.name ?? "Inventory item"} · issued row #${row.material_request_id}` : "Awaiting Store"}</td></tr>; })}</tbody></table></div></section>;
}

export function JobMaterialsPanel({ view, inventory, actor, mutate }: { view: JobView; inventory: InventoryItem[]; actor: User; mutate: Mutate }) {
  const materialJob = { ...view.job, materialApprovalStatus: view.material_approval?.status }; const editable = canManageMaterialRows(actor, materialJob); const [itemId, setItemId] = useState<number>(); const [qty, setQty] = useState(1); const [newItem, setNewItem] = useState({ item_name: "", quantity: 1, unit: "piece" }); const [error, setError] = useState("");
  const add = () => { if (itemId === undefined) { setError("Choose an item."); return; } if (mutate((db) => addMaterialRowForActor(db, view.job.id, actor.id, itemId, qty), setError)) { setItemId(undefined); setQty(1); } };
  const requestNew = () => { if (mutate((db) => createMaterialPurchaseRequestForActor(db, view.job.id, actor.id, newItem), setError)) setNewItem({ item_name: "", quantity: 1, unit: "piece" }); };
  return <section className="editor-block job-card-materials" aria-label="Job materials"><h4>Materials</h4>{!editable ? <p className="permission-note">Materials are locked because this job is {view.job.main_status}. Only the Owner or linked Service Advisor may request items while it is IN_PROGRESS.</p> : <><div className="material-add"><label>Item<InventoryPicker inventory={inventory} value={itemId} onChange={setItemId} label="Item" /></label><label>Qty<input aria-label="Qty" type="number" min="0.01" step="0.01" value={qty} onChange={(event) => setQty(Number(event.target.value))} /></label><button type="button" className="primary-action" onClick={add}>Add Row</button></div><form className="material-new-item" onSubmit={(event) => { event.preventDefault(); requestNew(); }}><h5>Request New Item</h5><label>Item name<input required value={newItem.item_name} onChange={(event) => setNewItem({ ...newItem, item_name: event.target.value })} /></label><label>Quantity<input required type="number" min="0.01" step="0.01" value={newItem.quantity} onChange={(event) => setNewItem({ ...newItem, quantity: Number(event.target.value) })} /></label><label>Unit<input required value={newItem.unit} onChange={(event) => setNewItem({ ...newItem, unit: event.target.value })} /></label><button className="secondary-action">Request New Item</button></form></>}{error && <p className="error-text" role="alert">{error}</p>}<div className="material-table-scroll"><table aria-label="Material rows"><thead><tr><th>Item</th><th>Qty</th><th>Status</th><th>Actions</th></tr></thead><tbody>{view.material_requests.length ? view.material_requests.map((row) => <MaterialRow key={`${row.id}-${row.status}-${row.requested_qty}-${row.item_id}`} row={row} job={materialJob} inventory={inventory} actor={actor} mutate={mutate} />) : <tr><td colSpan={4}>No inventory material rows yet.</td></tr>}</tbody></table></div><PurchaseRequestTable rows={view.material_purchase_requests} inventory={inventory} /></section>;
}
