import { useEffect, useMemo, useRef, useState } from "react";
import { beginPlatformLogin, createPlatformApi, endPlatformSession, establishPlatformAuth, type PlatformAuth, type PlatformCognitoConfig, type PlatformLog, type PlatformSession, type PlatformTenant } from "./platform-admin-api";
import { activatePlatformEmulation } from "./platform-emulation-fetch";
import { DirtyFormDialog } from "./dialog-primitives";
import "./platform-admin.css";
import "./platform-recovery.css";

const identities=["platform-admin","platform-approver","support-agent"];
const now=()=>new Date().toISOString();
export default function PlatformAdminApp(){
  const [identity,setIdentity]=useState("platform-admin"),[mfaAt,setMfaAt]=useState(now()),[auth,setAuth]=useState<PlatformAuth>({mode:"local",identity:"platform-admin",mfaAuthenticatedAt:now()}),[cognitoConfig,setCognitoConfig]=useState<PlatformCognitoConfig>(),[session,setSession]=useState<PlatformSession>(),[scope,setScope]=useState<PlatformTenant>(),[logs,setLogs]=useState<PlatformLog[]>([]),[grants,setGrants]=useState<any[]>([]),[emulations,setEmulations]=useState<any[]>([]),[error,setError]=useState(""),[notice,setNotice]=useState(""),[signedOut,setSignedOut]=useState(false);
  const api=useMemo(()=>createPlatformApi(auth),[auth]);
  const can=(permission:string)=>session?.principal.permissions.includes(permission)??false;
  async function refresh(){setError("");try{const next=await api.session();setSession(next);const tenantId=scope?.tenant.id??next.tenants[0]?.id;if(tenantId)setScope(await api.tenant(tenantId));if(next.principal.permissions.some(p=>p.startsWith("platform.logs.")))setLogs((await api.logs()).logs);else setLogs([]);if(tenantId&&next.principal.permissions.some(p=>p.startsWith("platform.support.")||p.startsWith("platform.emulation.")))setGrants((await api.grants(tenantId)).grants);else setGrants([]);if(tenantId&&next.principal.permissions.some(p=>p.startsWith("platform.emulation.")))setEmulations((await api.emulations(tenantId)).emulations);else setEmulations([]);}catch(value){setError(value instanceof Error?value.message:String(value));}}
  useEffect(()=>{void establishPlatformAuth(identity,mfaAt).then(value=>{setCognitoConfig(value.config);if(value.auth)setAuth(value.auth);}).catch(value=>setError(value instanceof Error?value.message:String(value)));},[]);
  useEffect(()=>{void refresh();},[api]);
  async function command(action:()=>Promise<unknown>,message:string){setError("");try{await action();setNotice(message);await refresh();}catch(value){setError(value instanceof Error?value.message:String(value));}}
  async function selectTenant(tenantId:string){setError("");try{setScope(await api.tenant(tenantId));if(session?.principal.permissions.some(p=>p.startsWith("platform.support.")||p.startsWith("platform.emulation.")))setGrants((await api.grants(tenantId)).grants);else setGrants([]);if(session?.principal.permissions.some(p=>p.startsWith("platform.emulation.")))setEmulations((await api.emulations(tenantId)).emulations);else setEmulations([]);}catch(value){setError(value instanceof Error?value.message:String(value));}}
  function logout(){endPlatformSession(cognitoConfig);if(!cognitoConfig){setSession(undefined);setScope(undefined);setSignedOut(true);}}
  if(signedOut)return <main className="platform-admin platform-signed-out"><h1>Signed out of Platform Administration</h1><p>The platform-only session has ended.</p><button onClick={()=>{setSignedOut(false);void refresh();}}>Return to platform sign in</button></main>;
  return <main className="platform-admin"><header><div className="platform-heading"><div><p className="eyebrow">WorkshopOS platform operations</p><h1>Platform Super Admin</h1></div><div className="platform-account"><span><strong>{session?.principal.displayName??identity}</strong><small>Platform identity</small></span><button onClick={logout}>Logout</button></div></div><p>Separate platform-only workspace. Tenant navigation and ambient tenant access are intentionally unavailable.</p><div className="auth-panel">{cognitoConfig?<><span>Platform Cognito session with verified MFA</span><button onClick={()=>void beginPlatformLogin(cognitoConfig)}>Sign in / re-authenticate</button></>:<><label>Platform identity<select value={identity} onChange={event=>{const next=event.target.value,stamp=now();setIdentity(next);setMfaAt(stamp);setAuth({mode:"local",identity:next,mfaAuthenticatedAt:stamp});}}>{identities.map(value=><option key={value}>{value}</option>)}</select></label><button onClick={()=>{const stamp=now();setMfaAt(stamp);setAuth({mode:"local",identity,mfaAuthenticatedAt:stamp});}}>Re-authenticate with MFA</button><span>Recent MFA: {new Date(mfaAt).toLocaleTimeString()}</span></>}</div></header>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}{!session?<p>Establishing platform session...</p>:<>
    <section aria-labelledby="tenant-heading"><h2 id="tenant-heading">Explicit tenant scope</h2><label>Selected tenant<select value={scope?.tenant.id??""} onChange={event=>void selectTenant(event.target.value)}>{session.tenants.map(tenant=><option value={tenant.id} key={tenant.id}>{tenant.name}</option>)}</select></label>{scope&&<p>{scope.tenant.name} · {scope.branches.length} branches · {scope.users.length} active/non-archived users. Selection does not grant tenant access.</p>}</section>
    {can("platform.support.grant")&&scope&&<GrantForm key={scope.tenant.id} scope={scope} onSubmit={value=>command(()=>api.requestGrant(value),"Support grant requested for independent approval.")}/>}
    {can("platform.support.approve")&&<section><h2>Pending support grants</h2>{grants.filter(g=>g.status==="PENDING").length===0?<p>No pending grants.</p>:grants.filter(g=>g.status==="PENDING").map(g=><article key={g.id}><p>{g.supportIdentityId} · {g.reason}</p><button onClick={()=>void command(()=>api.approveGrant(g.id,"Scope independently verified"),"Support grant approved.")}>Approve grant</button></article>)}</section>}
    {can("platform.emulation.request")&&scope&&<EmulationForm key={scope.tenant.id} scope={scope} grants={grants.filter(g=>g.status==="ACTIVE"&&g.supportIdentityId===identity)} onSubmit={value=>command(()=>api.requestEmulation(value),"Emulation requested for independent approval.")}/>}
    {can("platform.emulation.approve")&&<section><h2>Pending emulation approvals</h2>{emulations.filter(e=>e.status==="PENDING").map(e=><article key={e.id}><p>{e.reason} · user {e.membershipId} · branch {e.branchId}</p><button onClick={()=>void command(()=>api.approveEmulation(e.id,"Exact scope independently verified"),"Emulation approved.")}>Approve emulation</button></article>)}</section>}
    {can("platform.emulation.use")&&<section><h2>Approved emulation</h2>{emulations.filter(e=>e.requestedBy===identity&&e.status==="APPROVED").map(e=><article key={e.id}><p>{e.reason}</p><button onClick={()=>void command(async()=>{const result=await api.startEmulation(e.id);activatePlatformEmulation(auth,result.emulation.id,result.emulation.expiresAt);},"15-minute emulation started." )}>Start 15-minute session</button></article>)}{emulations.filter(e=>e.requestedBy===identity&&e.status==="ACTIVE").map(e=><article key={e.id}><p><strong>Active until {new Date(e.expiresAt).toLocaleTimeString()}</strong>. Tenant actions use only the effective user's live permissions and ordinary approval rules.</p><a href={`/production?emulation=${encodeURIComponent(e.id)}`}>Open scoped tenant workspace</a></article>)}</section>}
    {can("platform.logs.read")&&<section><h2>Protected daily logs</h2><p>Logs remain online at least 30 days and recoverable through day 90. Every download and recovery is immutably audited.</p><div className="log-grid">{logs.map(log=><LogCard key={log.id} log={log} canDownload={can("platform.logs.download")} canRecover={can("platform.logs.recover")} onDownload={reason=>api.downloadLog(log.id,reason)} onRecover={reason=>command(()=>api.recoverLog(log.id,reason),"Log restored and checksum-verified for 24 hours.")}/>)}</div></section>}
  </>}</main>;
}
function GrantForm({scope,onSubmit}:{scope:PlatformTenant;onSubmit:(value:unknown)=>Promise<void>}){const initialBranch=scope.branches[0]?.id??"",[open,setOpen]=useState(false),[agent,setAgent]=useState("support-agent"),[branch,setBranch]=useState(initialBranch),[reason,setReason]=useState(""),[errors,setErrors]=useState<string[]>([]),focus=useRef<HTMLInputElement>(null);return <><section><h2>Support access</h2><p>Create an exact, independently approved grant.</p><button onClick={()=>{setErrors([]);setOpen(true)}}>Request support grant</button></section><DirtyFormDialog open={open} title="Request support grant" dirty={Boolean(reason||agent!=="support-agent"||branch!==initialBranch)} errors={errors} initialFocusRef={focus} submitLabel="Request grant" onClose={()=>setOpen(false)} onSubmit={event=>{event.preventDefault();const next=[!agent.trim()?"Enter a support identity.":"",!branch?"Choose an exact branch.":"",!reason.trim()?"Enter a reason.":""].filter(Boolean);setErrors(next);if(next.length)return;void onSubmit({tenantId:scope.tenant.id,supportIdentityId:agent,branchIds:[branch],permissions:["tenant.emulate"],reason:reason.trim(),expiresAt:new Date(Date.now()+60*60_000).toISOString()}).then(()=>setOpen(false));}}><label>Support identity<input ref={focus} value={agent} onChange={e=>setAgent(e.target.value)} required/></label><label>Exact branch<select value={branch} onChange={e=>setBranch(e.target.value)}>{scope.branches.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} required/></label></DirtyFormDialog></>}
function EmulationForm({scope,grants,onSubmit}:{scope:PlatformTenant;grants:any[];onSubmit:(value:unknown)=>Promise<void>}){const initialUser=scope.users[0]?.id??"",initialBranch=scope.branches[0]?.id??"",[open,setOpen]=useState(false),[grantId,setGrantId]=useState(""),[user,setUser]=useState(initialUser),[branch,setBranch]=useState(initialBranch),[reason,setReason]=useState(""),[errors,setErrors]=useState<string[]>([]),focus=useRef<HTMLSelectElement>(null);return <><section><h2>Tenant-user emulation</h2><p>Request exact user and branch scope from an active grant.</p><button onClick={()=>{setErrors([]);setOpen(true)}}>Request tenant-user emulation</button></section><DirtyFormDialog open={open} title="Request tenant-user emulation" dirty={Boolean(reason||grantId||user!==initialUser||branch!==initialBranch)} errors={errors} initialFocusRef={focus} submitLabel="Request emulation" onClose={()=>setOpen(false)} onSubmit={event=>{event.preventDefault();const next=[!grantId?"Choose an approved support grant.":"",!user?"Choose an effective tenant user.":"",!branch?"Choose an exact branch.":"",!reason.trim()?"Enter a reason.":""].filter(Boolean);setErrors(next);if(next.length)return;void onSubmit({grantId,tenantId:scope.tenant.id,membershipId:user,branchId:branch,reason:reason.trim()}).then(()=>setOpen(false));}}><label>Approved support grant<select ref={focus} required value={grantId} onChange={e=>setGrantId(e.target.value)}><option value="">Select grant</option>{grants.map(g=><option value={g.id} key={g.id}>{g.reason}</option>)}</select></label><label>Effective tenant user<select value={user} onChange={e=>setUser(e.target.value)}>{scope.users.map(item=><option value={item.id} key={item.id}>{item.displayName}</option>)}</select></label><label>Exact branch<select value={branch} onChange={e=>setBranch(e.target.value)}>{scope.branches.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Reason<textarea value={reason} onChange={e=>setReason(e.target.value)} required/></label></DirtyFormDialog></>}
function LogCard({log,canDownload,canRecover,onDownload,onRecover}:{log:PlatformLog;canDownload:boolean;canRecover:boolean;onDownload:(reason:string)=>Promise<void>;onRecover:(reason:string)=>Promise<void>}){const [reason,setReason]=useState("");return <article><h3>{log.date}</h3><p><strong>{log.restored?"RESTORED":log.tier}</strong></p><p>Online through {new Date(log.onlineUntil).toLocaleDateString()} · recoverable through {new Date(log.recoverableUntil).toLocaleDateString()}</p><label>Accountable reason<input value={reason} onChange={e=>setReason(e.target.value)} required/></label>{canDownload&&<button disabled={!reason||(!log.restored&&log.tier!=="ONLINE")} onClick={()=>void onDownload(reason)}>Download protected log</button>}{canRecover&&log.tier==="RECOVERABLE"&&!log.restored&&<button disabled={!reason} onClick={()=>void onRecover(reason)}>Recover and verify</button>}</article>}
