export type PlatformAuth = { mode:"local";identity:string;mfaAuthenticatedAt:string } | { mode:"cognito";accessToken:string;mfaAuthenticatedAt:string };
export type PlatformSession = { principal:{identityId:string;displayName:string;permissions:string[]};tenants:Array<{id:string;name:string;plan:string;timezone:string;version:number}> };
export type PlatformTenant = {tenant:{id:string;name:string;plan:string;timezone:string;version:number};branches:Array<{id:string;name:string;active:boolean}>;users:Array<{id:string;displayName:string;email:string;status:string;active:boolean}>};
export type PlatformLog = {id:string;date:string;objectKey:string;contentType:string;checksum:string;onlineUntil:string;recoverableUntil:string;tier:"ONLINE"|"RECOVERABLE"|"EXPIRED";restored:boolean};
export type PlatformCognitoConfig={mode:"cognito";clientId:string;authorizationEndpoint:string;tokenEndpoint:string;logoutEndpoint:string;callbackUri:string;logoutUri:string;scopes:string[]};
const PLATFORM_TOKEN_KEY="workshopos.platform.tokens.v1",PLATFORM_OAUTH_KEY="workshopos.platform.oauth.v1";
const base64Url=(bytes:Uint8Array)=>btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
const randomValue=()=>{const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return base64Url(bytes);};
async function digest(value:string){return base64Url(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value))));}
export async function establishPlatformAuth(localIdentity:string,mfaAuthenticatedAt:string):Promise<{auth?:PlatformAuth;config?:PlatformCognitoConfig}>{const config=await fetch("/api/v1/platform/auth/config").then(response=>response.json()) as PlatformCognitoConfig|{mode:"local"};if(config.mode==="local")return{auth:{mode:"local",identity:localIdentity,mfaAuthenticatedAt}};const params=new URLSearchParams(location.search),code=params.get("code");if(code){const saved=sessionStorage.getItem(PLATFORM_OAUTH_KEY),oauth=saved?JSON.parse(saved) as {verifier:string;state:string}:undefined;if(!oauth||params.get("state")!==oauth.state)throw new Error("Platform sign-in state was invalid.");const response=await fetch(config.tokenEndpoint,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"authorization_code",client_id:config.clientId,code,redirect_uri:config.callbackUri,code_verifier:oauth.verifier})});if(!response.ok)throw new Error("Platform sign-in could not be completed.");const value=await response.json() as {access_token:string;expires_in:number};sessionStorage.setItem(PLATFORM_TOKEN_KEY,JSON.stringify({accessToken:value.access_token,expiresAt:Date.now()+value.expires_in*1000}));sessionStorage.removeItem(PLATFORM_OAUTH_KEY);history.replaceState({},document.title,"/platform");}const saved=sessionStorage.getItem(PLATFORM_TOKEN_KEY),token=saved?JSON.parse(saved) as {accessToken:string;expiresAt:number}:undefined;return token&&token.expiresAt>Date.now()+30_000?{auth:{mode:"cognito",accessToken:token.accessToken,mfaAuthenticatedAt:new Date().toISOString()},config}:{config};}
export async function beginPlatformLogin(config:PlatformCognitoConfig){const verifier=randomValue(),state=randomValue();sessionStorage.setItem(PLATFORM_OAUTH_KEY,JSON.stringify({verifier,state}));const url=new URL(config.authorizationEndpoint);url.search=new URLSearchParams({client_id:config.clientId,response_type:"code",redirect_uri:config.callbackUri,scope:config.scopes.join(" "),state,code_challenge_method:"S256",code_challenge:await digest(verifier)}).toString();location.assign(url);}

function headers(auth:PlatformAuth,write=false):HeadersInit{return {accept:"application/json",...(write?{"content-type":"application/json"}:{}),...(auth.mode==="local"?{"x-workshopos-platform-mfa-at":auth.mfaAuthenticatedAt,"x-workshopos-platform-identity":auth.identity}:{"x-workshopos-platform-authorization":`Bearer ${auth.accessToken}`})};}
async function checked<T>(response:Response):Promise<T>{if(!response.ok){const value=await response.json().catch(()=>({})) as {code?:string;message?:string;traceId?:string};throw new Error(`${value.message??value.code??"Platform request failed"}${value.traceId?` (trace ${value.traceId})`:""}`);}return response.json() as Promise<T>;}
export function createPlatformApi(auth:PlatformAuth){const get=async<T>(path:string)=>checked<T>(await fetch(path,{headers:headers(auth)}));const post=async<T>(path:string,value:unknown)=>checked<T>(await fetch(path,{method:"POST",headers:headers(auth,true),body:JSON.stringify(value)}));return{
  session:()=>get<PlatformSession>("/api/v1/platform/session"),tenant:(id:string)=>get<PlatformTenant>(`/api/v1/platform/tenants/${id}`),
  grants:(tenantId:string)=>get<{grants:any[]}>(`/api/v1/platform/support-grants?tenantId=${encodeURIComponent(tenantId)}`),requestGrant:(input:unknown)=>post<{grant:any}>("/api/v1/platform/support-grants",input),approveGrant:(id:string,reason:string)=>post<{grant:any}>(`/api/v1/platform/support-grants/${id}/approve`,{reason}),
  emulations:(tenantId:string)=>get<{emulations:any[]}>(`/api/v1/platform/emulations?tenantId=${encodeURIComponent(tenantId)}`),requestEmulation:(input:unknown)=>post<{emulation:any}>("/api/v1/platform/emulations",input),approveEmulation:(id:string,reason:string)=>post<{emulation:any}>(`/api/v1/platform/emulations/${id}/approve`,{reason}),startEmulation:(id:string)=>post<{emulation:any}>(`/api/v1/platform/emulations/${id}/start`,{}),
  logs:()=>get<{logs:PlatformLog[]}>("/api/v1/platform/logs"),recoverLog:(id:string,reason:string)=>post<{recovery:any}>(`/api/v1/platform/logs/${id}/recover`,{reason}),
  async downloadLog(id:string,reason:string){const response=await fetch(`/api/v1/platform/logs/${id}/download?reason=${encodeURIComponent(reason)}`,{headers:headers(auth)});if(!response.ok)await checked(response);const blob=await response.blob(),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=response.headers.get("content-disposition")?.match(/filename="([^"]+)"/)?.[1]??"workshopos-log.ndjson";anchor.click();URL.revokeObjectURL(url);},
  emulationHeaders:(id:string):HeadersInit=>({...headers(auth),"x-workshopos-emulation-id":id}),
};}
