import { type FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { loadAuthConfig, loadWorkshopSession } from "./auth";
import { DirtyFormDialog } from "./dialog-primitives";
import { createCustomersVehiclesApi, IdentityApiError, type Customer, type EntityListQuery, type IdentityAuth, type Vehicle } from "./production-customers-vehicles-api";
import { DEFAULT_WORK_ITEM_LIST_QUERY } from "./work-items-api";
import "./production-work-items.css";

type Kind = "customers" | "vehicles";
type Ready = { auth: IdentityAuth; session: any };
function queryFromUrl(): EntityListQuery { const p = new URLSearchParams(location.search); const size = Number(p.get("pageSize")); const sort = p.get("sort"); return { search: p.get("search") ?? "", branchId: p.get("branchId") ?? "", sort: (["updatedAt.desc","updatedAt.asc","summary.asc","summary.desc"].includes(sort ?? "") ? sort : "updatedAt.desc") as EntityListQuery["sort"], page: Math.max(1, Number(p.get("page") ?? 1)), pageSize: ([25,50,100].includes(size) ? size : 25) as 25|50|100 }; }
function readable(error: unknown) { return error instanceof IdentityApiError ? `${error.message} Reference: ${error.traceId}` : "WorkshopOS could not complete the request."; }

function Screen({ ready, kind }: { ready: Ready; kind: Kind }) {
  const api = useMemo(() => createCustomersVehiclesApi(ready.auth), [ready.auth]); const [query,setQuery] = useState(queryFromUrl); const [draft,setDraft] = useState(query.search); const [rows,setRows] = useState<(Customer|Vehicle)[]>([]); const [owners,setOwners] = useState<Customer[]>([]); const [page,setPage] = useState({page:1,pageSize:25,totalCount:0,pageCount:1}); const [view,setView] = useState<"grid"|"table">("table"); const [open,setOpen] = useState(false); const [editing,setEditing] = useState<Customer|Vehicle>(); const [detail,setDetail] = useState<Customer|Vehicle>(); const [form,setForm] = useState<any>({}); const [busy,setBusy] = useState(false); const [failure,setFailure] = useState(""); const [status,setStatus] = useState(""); const [errors,setErrors] = useState<string[]>([]); const focus = useRef<HTMLInputElement>(null);
  const branches = ready.session.membership.branches as Array<{id:string;name:string}>; const permissions = ready.session.membership.permissions as string[]; const read = kind === "customers" ? "customer.read" : "vehicle.read"; const manage = kind === "customers" ? "customer.manage" : "vehicle.manage"; const exportPermission = kind === "customers" ? "customer.export" : "vehicle.export"; const title = kind === "customers" ? "Customers" : "Vehicles";
  async function load(next=query) { setBusy(true); try { if (kind === "customers") { const result=await api.listCustomers(next); setRows(result.customers); setPage(result.page); } else { const result=await api.listVehicles(next); setRows(result.vehicles); setPage(result.page); } setFailure(""); } catch(e){setFailure(readable(e));} finally{setBusy(false);} }
  useEffect(()=>{ void load(); void api.getPreference(kind).then((p)=>setView(p.viewMode)); if(kind==="vehicles")void api.listCustomers({...DEFAULT_WORK_ITEM_LIST_QUERY,pageSize:100}).then(result=>setOwners(result.customers)); },[kind]);
  function navigate(next: EntityListQuery) { const p = new URLSearchParams(); if(next.search)p.set("search",next.search);if(next.branchId)p.set("branchId",next.branchId);if(next.sort!=="updatedAt.desc")p.set("sort",next.sort);if(next.page!==1)p.set("page",String(next.page));if(next.pageSize!==25)p.set("pageSize",String(next.pageSize));history.pushState({},"",`${location.pathname}${p.size?`?${p}`:""}`);setQuery(next);void load(next); }
  function blank(){ return kind === "customers" ? { branchId:branches[0]?.id??"",displayName:"",mobile:"",email:"" } : { branchId:branches[0]?.id??"",registration:"",vin:"",make:"",model:"",ownerCustomerId:"" }; }
  function startCreate(){setEditing(undefined);setForm(blank());setErrors([]);setOpen(true);} function startEdit(row: Customer|Vehicle){setEditing(row);setForm({...row});setErrors([]);setOpen(true);}
  async function viewDetail(row: Customer|Vehicle){setBusy(true);try{setDetail(kind==="customers"?await api.getCustomer(row.id):await api.getVehicle(row.id));setFailure("");}catch(e){setFailure(readable(e));}finally{setBusy(false);}}
  async function submit(event: FormEvent){event.preventDefault();const nextErrors=kind==="customers"?[!form.displayName?.trim()?"Enter a customer name.":"",!/^(?:\D*\d){10,12}\D*$/.test(form.mobile??"")?"Enter a valid mobile number.":""].filter(Boolean):[!form.registration?.trim()&&!form.vin?.trim()?"Enter a registration or VIN.":"",!form.ownerCustomerId?"Choose an owner.":""].filter(Boolean);setErrors(nextErrors);if(nextErrors.length)return;setBusy(true);try{if(kind==="customers")editing?await api.updateCustomer(form):await api.createCustomer(form);else editing?await api.updateVehicle(form):await api.createVehicle(form);setOpen(false);setStatus(`${title.slice(0,-1)} saved.`);await load();}catch(e){setErrors([readable(e)]);}finally{setBusy(false);}}
  async function choose(next:"grid"|"table"){setView(next);try{await api.savePreference(kind,next);}catch(e){setFailure(readable(e));}}
  async function exportRows(format:"PDF"|"XLSX"){setBusy(true);try{let job=await api.requestExport(kind,format,query);for(let i=0;i<20&&job.status==="PENDING";i++){await new Promise(r=>setTimeout(r,100));job=await api.getExport(job.id);}if(job.status!=="READY")throw new Error();const download=await api.downloadExport(job.id);const url=URL.createObjectURL(download.blob);const a=document.createElement("a");a.href=url;a.download=download.filename;a.click();URL.revokeObjectURL(url);setStatus(`${format} export ready: ${job.rowCount??0} rows.`);}catch(e){setFailure(readable(e));}finally{setBusy(false);}}
  return <main className="v12-work-items"><header><a href="/">Back to WorkshopOS</a><h1>{title}</h1><p>Authenticated PostgreSQL records for your permitted branches.</p></header>{failure&&<p role="alert">{failure}</p>}{status&&<p role="status">{status}</p>}{detail&&<section aria-labelledby="identity-detail"><h2 id="identity-detail">{kind==="customers"?(detail as Customer).displayName:(detail as Vehicle).registration||(detail as Vehicle).vin}</h2>{"displayName" in detail?<p>Mobile: {detail.mobile}. Email: {detail.email||"Not recorded"}.</p>:<p>{detail.make} {detail.model}. Owner: {detail.ownerName}. VIN: {detail.vin||"Not recorded"}.</p>}<p>Record version {detail.version}</p><button type="button" onClick={()=>setDetail(undefined)}>Close details</button></section>}<section><div className="ws-tracer-actions"><h2>{title} directory</h2>{permissions.includes(manage)&&<button onClick={startCreate}>Create {title.slice(0,-1).toLowerCase()}</button>}<button onClick={()=>void load()} disabled={busy}>Refresh</button></div>
    <form className="v12-list-controls" role="search" onSubmit={e=>{e.preventDefault();navigate({...query,search:draft.trim(),page:1});}}><label htmlFor="identity-search">Search</label><input id="identity-search" value={draft} onChange={e=>setDraft(e.target.value)}/><label htmlFor="identity-branch">Branch</label><select id="identity-branch" value={query.branchId} onChange={e=>navigate({...query,branchId:e.target.value,page:1})}><option value="">All permitted branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><label htmlFor="identity-sort">Sort</label><select id="identity-sort" value={query.sort} onChange={e=>navigate({...query,sort:e.target.value as any,page:1})}><option value="updatedAt.desc">Recently updated</option><option value="updatedAt.asc">Oldest updated</option><option value="summary.asc">Name A–Z</option><option value="summary.desc">Name Z–A</option></select><button>Apply</button><button type="button" onClick={()=>{setDraft("");navigate(DEFAULT_WORK_ITEM_LIST_QUERY);}}>Clear</button></form>
    <div className="v12-presentation"><div role="group" aria-label="View mode"><button aria-pressed={view==="table"} onClick={()=>void choose("table")}>Table</button><button aria-pressed={view==="grid"} onClick={()=>void choose("grid")}>Grid</button></div>{permissions.includes(exportPermission)&&<><button onClick={()=>void exportRows("PDF")}>Export PDF</button><button onClick={()=>void exportRows("XLSX")}>Export XLSX</button></>}</div>
    {!busy&&!rows.length?<div className="v12-empty"><p>{query.search||query.branchId?`No ${kind} match these filters.`:`No ${kind} in your permitted branches.`}</p><button onClick={()=>{setDraft("");navigate(DEFAULT_WORK_ITEM_LIST_QUERY);}}>Clear filters</button></div>:view==="table"?<div className="v12-table-wrap"><table><thead><tr>{kind==="customers"?<><th>Name</th><th>Mobile</th><th>Email</th></>:<><th>Registration</th><th>Vehicle</th><th>Owner</th></>}<th>Branch</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}>{"displayName" in row?<><td>{row.displayName}</td><td>{row.mobile}</td><td>{row.email||"—"}</td></>:<><td>{row.registration||row.vin}</td><td>{row.make} {row.model}</td><td>{row.ownerName}</td></>}<td>{branches.find(b=>b.id===row.branchId)?.name??"Permitted branch"}</td><td><button onClick={()=>void viewDetail(row)}>View {"displayName" in row?row.displayName:row.registration||row.vin}</button>{permissions.includes(manage)&&<button onClick={()=>startEdit(row)}>Edit {"displayName" in row?row.displayName:row.registration}</button>}</td></tr>)}</tbody></table></div>:<ul className="v12-card-grid">{rows.map(row=><li key={row.id}><strong>{"displayName" in row?row.displayName:row.registration}</strong><small>{"displayName" in row?row.mobile:`${row.make} ${row.model} · ${row.ownerName}`}</small><button onClick={()=>void viewDetail(row)}>View details</button>{permissions.includes(manage)&&<button onClick={()=>startEdit(row)}>Edit</button>}</li>)}</ul>}
    <nav className="v12-pagination" aria-label={`${title} pages`}><span>{page.totalCount?`${(page.page-1)*page.pageSize+1}–${Math.min(page.page*page.pageSize,page.totalCount)} of ${page.totalCount}`:"0 results"}</span><button disabled={page.page<=1||busy} onClick={()=>navigate({...query,page:page.page-1})}>Previous</button><span>Page {page.page} of {page.pageCount}</span><button disabled={page.page>=page.pageCount||busy} onClick={()=>navigate({...query,page:page.page+1})}>Next</button><label htmlFor="identity-size">Rows</label><select id="identity-size" value={query.pageSize} onChange={e=>navigate({...query,pageSize:Number(e.target.value) as any,page:1})}><option>25</option><option>50</option><option>100</option></select></nav></section>
    <DirtyFormDialog open={open} title={`${editing?"Edit":"Create"} ${title.slice(0,-1).toLowerCase()}`} dirty={Boolean(Object.values(form).some(Boolean))} errors={errors} busy={busy} initialFocusRef={focus} submitLabel="Save" onSubmit={submit} onClose={()=>setOpen(false)}>{kind==="customers"?<><label htmlFor="customer-name">Name</label><input ref={focus} id="customer-name" value={form.displayName??""} onChange={e=>setForm({...form,displayName:e.target.value})}/><label htmlFor="customer-mobile">Mobile</label><input id="customer-mobile" value={form.mobile??""} onChange={e=>setForm({...form,mobile:e.target.value})}/><label htmlFor="customer-email">Email</label><input id="customer-email" type="email" value={form.email??""} onChange={e=>setForm({...form,email:e.target.value})}/></>:<><label htmlFor="vehicle-registration">Registration</label><input ref={focus} id="vehicle-registration" value={form.registration??""} onChange={e=>setForm({...form,registration:e.target.value})}/><label htmlFor="vehicle-vin">VIN</label><input id="vehicle-vin" value={form.vin??""} onChange={e=>setForm({...form,vin:e.target.value})}/><label htmlFor="vehicle-make">Make</label><input id="vehicle-make" value={form.make??""} onChange={e=>setForm({...form,make:e.target.value})}/><label htmlFor="vehicle-model">Model</label><input id="vehicle-model" value={form.model??""} onChange={e=>setForm({...form,model:e.target.value})}/><label htmlFor="vehicle-owner">Owner customer</label><select id="vehicle-owner" value={form.ownerCustomerId??""} onChange={e=>setForm({...form,ownerCustomerId:e.target.value})}><option value="">Choose owner</option>{owners.filter(owner=>owner.branchId===(form.branchId??editing?.branchId)).map(owner=><option key={owner.id} value={owner.id}>{owner.displayName} · {owner.mobile}</option>)}</select></>} {!editing&&<><label htmlFor="identity-form-branch">Branch</label><select id="identity-form-branch" value={form.branchId??""} onChange={e=>setForm({...form,branchId:e.target.value,ownerCustomerId:""})}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></>}</DirtyFormDialog></main>;
}

export default function ProductionCustomersVehiclesApp(){const kind:Kind=location.pathname.endsWith("vehicles")?"vehicles":"customers";const [ready,setReady]=useState<Ready>();const [error,setError]=useState("");useEffect(()=>{void(async()=>{try{const config=await loadAuthConfig();let auth:IdentityAuth;let session;if(config.mode==="local"){if(!config.allowDemo)throw new Error();auth={mode:"local",identity:"north-admin"};session=await createCustomersVehiclesApi(auth).session();}else{session=await loadWorkshopSession(config);if(!session)throw new Error();auth={mode:"cognito",config};}const read=kind==="customers"?"customer.read":"vehicle.read";const page=kind==="customers"?"customers.page":"vehicles.page";if(!session.membership.permissions.includes(read)||!session.membership.permissions.includes(page)){setError(`You do not have permission to view ${kind}.`);return;}setReady({auth,session});}catch{setError(`WorkshopOS could not establish the ${kind} session.`);}})();},[kind]);if(error)return <main><h1>{kind}</h1><p role="alert">{error}</p></main>;if(!ready)return <main><p>Loading {kind}…</p></main>;return <Screen ready={ready} kind={kind}/>;}
