import { type FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { loadAuthConfig, loadWorkshopSession } from "./auth";
import { DirtyFormDialog } from "./dialog-primitives";
import { ProductionNavigation } from "./ProductionNavigation";
import { createInventoryApi, InventoryApiError, type InventoryAuth, type InventoryImport, type InventoryListQuery, type InventoryPosition } from "./production-inventory-api";
import { DEFAULT_WORK_ITEM_LIST_QUERY } from "./work-items-api";
import "./production-work-items.css";

function readable(error: unknown) { return error instanceof InventoryApiError ? `${error.message} Reference: ${error.traceId}` : "WorkshopOS could not complete the inventory request."; }
function fromUrl(): InventoryListQuery { const p=new URLSearchParams(location.search),size=Number(p.get("pageSize")),sort=p.get("sort"); return { search:p.get("search")??"",branchId:p.get("branchId")??"",sort:(["updatedAt.desc","updatedAt.asc","summary.asc","summary.desc"].includes(sort??"")?sort:"updatedAt.desc") as InventoryListQuery["sort"],page:Math.max(1,Number(p.get("page")??1)),pageSize:([25,50,100].includes(size)?size:25) as 25|50|100 }; }
function parseCsv(value:string){const lines=value.trim().split(/\r?\n/).filter(Boolean);const start=/sku/i.test(lines[0]??"")?1:0;return lines.slice(start).map(line=>{const [sku,warehouseCode,quantity,valueMinor]=line.split(",").map(cell=>cell.trim());return{sku,warehouseCode,quantity,valueMinor};});}

function InventoryScreen({auth,session}:{auth:InventoryAuth;session:any}){const api=useMemo(()=>createInventoryApi(auth),[auth]);const [query,setQuery]=useState(fromUrl);const [draft,setDraft]=useState(query.search);const [rows,setRows]=useState<InventoryPosition[]>([]);const [analytics,setAnalytics]=useState<any>({});const [page,setPage]=useState<any>({page:1,pageSize:25,totalCount:0,pageCount:1});const [view,setView]=useState<"grid"|"table">("table");const [busy,setBusy]=useState(false);const [failure,setFailure]=useState("");const [status,setStatus]=useState("");const [receipt,setReceipt]=useState<any>();const [importOpen,setImportOpen]=useState(false);const [importForm,setImportForm]=useState({branchId:session.membership.branches[0]?.id??"",filename:"inventory.csv",csv:"sku,warehouseCode,quantity,valueMinor\n"});const [staged,setStaged]=useState<InventoryImport>();const [errors,setErrors]=useState<string[]>([]);const focus=useRef<HTMLInputElement>(null);const permissions=session.membership.permissions as string[];const branches=session.membership.branches as Array<{id:string;name:string}>;
  async function load(next=query){setBusy(true);try{const result=await api.list(next);setRows(result.inventory);setAnalytics(result.analytics);setPage(result.page);setFailure("");}catch(e){setFailure(readable(e));}finally{setBusy(false);}}
  useEffect(()=>{void load();void api.getPreference().then(p=>setView(p.viewMode));},[]);
  function navigate(next:InventoryListQuery){const p=new URLSearchParams();if(next.search)p.set("search",next.search);if(next.branchId)p.set("branchId",next.branchId);if(next.sort!=="updatedAt.desc")p.set("sort",next.sort);if(next.page!==1)p.set("page",String(next.page));if(next.pageSize!==25)p.set("pageSize",String(next.pageSize));history.pushState({},"",`${location.pathname}${p.size?`?${p}`:""}`);setQuery(next);void load(next);}
  async function exportRows(format:"PDF"|"XLSX"){setBusy(true);try{let job=await api.requestExport(format,query);for(let i=0;i<20&&job.status==="PENDING";i++){await new Promise(r=>setTimeout(r,100));job=await api.getExport(job.id);}if(job.status!=="READY")throw new Error();const file=await api.downloadExport(job.id),url=URL.createObjectURL(file.blob),a=document.createElement("a");a.href=url;a.download=file.filename;a.click();URL.revokeObjectURL(url);setStatus(`${format} export ready: ${job.rowCount??0} rows.`);}catch(e){setFailure(readable(e));}finally{setBusy(false);}}
  async function submitReceipt(e:FormEvent){e.preventDefault();setBusy(true);try{await api.receive(receipt);setReceipt(undefined);setStatus("Stock receipt posted to the append-only ledger.");await load();}catch(error){setErrors([readable(error)]);}finally{setBusy(false);}}
  async function stage(e:FormEvent){e.preventDefault();const parsed=parseCsv(importForm.csv);if(!parsed.length){setErrors(["Add at least one inventory row."]);return;}setBusy(true);try{const result=await api.stageImport({...importForm,rows:parsed});setStaged(result);setImportOpen(false);setStatus("Import staged and dry-run complete. No stock changed.");}catch(error){setErrors([readable(error)]);}finally{setBusy(false);}}
  async function commit(){if(!staged)return;setBusy(true);try{const result=await api.commitImport(staged);setStaged(result.import);setStatus(`Import committed: ${result.reconciliation?.ledgerBatches??0} ledger batches reconciled.`);await load();}catch(error){setFailure(readable(error));}finally{setBusy(false);}}
  async function manifest(){if(!staged)return;const file=await api.downloadManifest(staged.id),url=URL.createObjectURL(file.blob),a=document.createElement("a");a.href=url;a.download=file.filename;a.click();URL.revokeObjectURL(url);}
  return <main className="v12-work-items"><header><a href="/">Back to WorkshopOS</a><h1>Inventory</h1><p>Production stock position, movement, ageing, reorder, and controlled imports.</p><ProductionNavigation permissions={permissions}/></header>{failure&&<p role="alert">{failure}</p>}{status&&<p role="status">{status}</p>}
    <section aria-label="Inventory analytics" className="v12-card-grid"><article><strong>{analytics.skuCount??0}</strong><small>Filtered positions</small></article><article><strong>{analytics.totalQuantity??0}</strong><small>Total quantity</small></article><article><strong>{analytics.totalValueMinor??0}</strong><small>Value (minor units)</small></article><article><strong>{analytics.reorderCount??0}</strong><small>Reorder alerts</small></article></section>
    <section><div className="ws-tracer-actions"><h2>Stock positions</h2><button onClick={()=>void load()} disabled={busy}>Refresh</button>{permissions.includes("inventory.import")&&<button onClick={()=>{setErrors([]);setImportOpen(true)}}>Stage import</button>}</div><form role="search" className="v12-list-controls" onSubmit={e=>{e.preventDefault();navigate({...query,search:draft.trim(),page:1})}}><label htmlFor="inventory-search">Search</label><input id="inventory-search" value={draft} onChange={e=>setDraft(e.target.value)}/><label htmlFor="inventory-branch">Branch</label><select id="inventory-branch" value={query.branchId} onChange={e=>navigate({...query,branchId:e.target.value,page:1})}><option value="">All permitted branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><label htmlFor="inventory-sort">Sort</label><select id="inventory-sort" value={query.sort} onChange={e=>navigate({...query,sort:e.target.value as InventoryListQuery["sort"],page:1})}><option value="updatedAt.desc">Recent movement</option><option value="updatedAt.asc">Oldest movement</option><option value="summary.asc">SKU A–Z</option><option value="summary.desc">SKU Z–A</option></select><button>Apply</button><button type="button" onClick={()=>{setDraft("");navigate(DEFAULT_WORK_ITEM_LIST_QUERY)}}>Clear</button></form><div className="v12-presentation"><div role="group" aria-label="View mode"><button aria-pressed={view==="table"} onClick={()=>{setView("table");void api.savePreference("table")}}>Table</button><button aria-pressed={view==="grid"} onClick={()=>{setView("grid");void api.savePreference("grid")}}>Grid</button></div>{permissions.includes("inventory.export")&&<><button onClick={()=>void exportRows("PDF")}>Export PDF</button><button onClick={()=>void exportRows("XLSX")}>Export XLSX</button></>}</div>
    {!busy&&!rows.length?<div className="v12-empty"><p>No inventory positions match these filters.</p><button onClick={()=>navigate(DEFAULT_WORK_ITEM_LIST_QUERY)}>Clear filters</button></div>:view==="table"?<div className="v12-table-wrap"><table><thead><tr><th>SKU</th><th>Warehouse</th><th>Quantity</th><th>Value</th><th>Age</th><th>Indicator</th><th>Action</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.id}:${row.warehouseId}`}><td>{row.sku}</td><td>{row.warehouseName}</td><td>{row.quantity} {row.baseUom}</td><td>{row.valueMinor}</td><td>{row.ageDays===undefined?"Never moved":`${row.ageDays} days`}</td><td>{row.reorder?"Reorder":"In stock"}</td><td>{permissions.includes("inventory.operate")&&<button onClick={()=>{setErrors([]);setReceipt({branchId:row.branchId,warehouseId:row.warehouseId,itemId:row.id,quantity:"",valueMinor:"",reason:""})}}>Receive</button>}</td></tr>)}</tbody></table></div>:<ul className="v12-card-grid">{rows.map(row=><li key={`${row.id}:${row.warehouseId}`}><strong>{row.sku}</strong><small>{row.warehouseName} · {row.quantity} {row.baseUom}</small><span>{row.reorder?"Reorder required":"In stock"}</span>{permissions.includes("inventory.operate")&&<button onClick={()=>{setErrors([]);setReceipt({branchId:row.branchId,warehouseId:row.warehouseId,itemId:row.id,quantity:"",valueMinor:"",reason:""})}}>Receive {row.sku}</button>}</li>)}</ul>}
    <nav className="v12-pagination" aria-label="Inventory pages"><span>{page.totalCount?`${(page.page-1)*page.pageSize+1}–${Math.min(page.page*page.pageSize,page.totalCount)} of ${page.totalCount}`:"0 results"}</span><button disabled={page.page<=1||busy} onClick={()=>navigate({...query,page:page.page-1})}>Previous</button><span>Page {page.page} of {page.pageCount}</span><button disabled={page.page>=page.pageCount||busy} onClick={()=>navigate({...query,page:page.page+1})}>Next</button><label htmlFor="inventory-size">Rows</label><select id="inventory-size" value={query.pageSize} onChange={e=>navigate({...query,pageSize:Number(e.target.value) as 25|50|100,page:1})}><option>25</option><option>50</option><option>100</option></select></nav></section>
    {staged&&<section aria-labelledby="dry-run"><h2 id="dry-run">Import dry run</h2><p>{staged.summary.validRows} valid; {staged.summary.invalidRows} rejected; quantity {staged.summary.quantity}; value {staged.summary.valueMinor}.</p>{staged.summary.invalidRows>0&&<button onClick={()=>void manifest()}>Download error manifest</button>}{staged.status==="STAGED"&&staged.summary.invalidRows===0&&<button onClick={()=>void commit()} disabled={busy}>Commit validated import</button>}{staged.reconciliation&&<p>Reconciled {staged.reconciliation.ledgerBatches} ledger batches, quantity {staged.reconciliation.quantity}, value {staged.reconciliation.valueMinor}.</p>}</section>}
    <DirtyFormDialog open={Boolean(receipt)} title="Receive stock" dirty={Boolean(receipt?.quantity||receipt?.valueMinor||receipt?.reason)} errors={errors} busy={busy} initialFocusRef={focus} submitLabel="Post receipt" onSubmit={submitReceipt} onClose={()=>setReceipt(undefined)}><label htmlFor="receipt-quantity">Quantity</label><input ref={focus} id="receipt-quantity" inputMode="decimal" value={receipt?.quantity??""} onChange={e=>setReceipt({...receipt,quantity:e.target.value})}/><label htmlFor="receipt-value">Value in minor units</label><input id="receipt-value" inputMode="numeric" value={receipt?.valueMinor??""} onChange={e=>setReceipt({...receipt,valueMinor:e.target.value})}/><label htmlFor="receipt-reason">Reason</label><textarea id="receipt-reason" value={receipt?.reason??""} onChange={e=>setReceipt({...receipt,reason:e.target.value})}/></DirtyFormDialog>
    <DirtyFormDialog open={importOpen} title="Stage inventory import" dirty={importForm.csv.trim().length>0} errors={errors} busy={busy} initialFocusRef={focus} submitLabel="Validate dry run" onSubmit={stage} onClose={()=>setImportOpen(false)}><label htmlFor="import-branch">Branch</label><select ref={focus as any} id="import-branch" value={importForm.branchId} onChange={e=>setImportForm({...importForm,branchId:e.target.value})}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><label htmlFor="import-filename">Filename</label><input id="import-filename" value={importForm.filename} onChange={e=>setImportForm({...importForm,filename:e.target.value})}/><label htmlFor="import-rows">CSV rows</label><textarea id="import-rows" rows={8} value={importForm.csv} onChange={e=>setImportForm({...importForm,csv:e.target.value})}/><small>Columns: sku, warehouseCode, quantity, valueMinor. Dry run does not change stock.</small></DirtyFormDialog>
  </main>}

export default function ProductionInventoryApp(){const [ready,setReady]=useState<{auth:InventoryAuth;session:any}>();const [error,setError]=useState("");useEffect(()=>{void(async()=>{try{const config=await loadAuthConfig();let auth:InventoryAuth,session;if(config.mode==="local"){if(!config.allowDemo)throw new Error();auth={mode:"local",identity:"north-admin"};session=await createInventoryApi(auth).session();}else{session=await loadWorkshopSession(config);if(!session)throw new Error();auth={mode:"cognito",config};}if(!session.membership.permissions.includes("inventory.page")||!session.membership.permissions.includes("inventory.read")){setError("You do not have permission to view Inventory.");return;}setReady({auth,session});}catch{setError("WorkshopOS could not establish the Inventory session.");}})()},[]);if(error)return <main><h1>Inventory</h1><p role="alert">{error}</p></main>;if(!ready)return <main><p>Loading Inventory…</p></main>;return <InventoryScreen {...ready}/>;}
