import { Download, Plus, Printer } from "lucide-react";
import { useEffect, useId, useMemo, useState, type FormEvent } from "react";
import { printRenderedDocument } from "./job-documents";
import { renderHtmlToPdf } from "./pdf-render";
import { renderReportTemplate, rupeesInWords, type ReportLine } from "./report-templates";
import { salesApi, type Lead, type Quotation, type QuotationDocument, type QuotationLine, type ServiceTask } from "./sales-api";
import type { CognitoConfig } from "./auth";
import { Dialog } from "./ui-kit";

export type Template = { id: string; name: string; html: string; active?: boolean };
export type QuotationInput = { leadId: number; validUntil?: string; customerNotes?: string; discount?: number; templateId: string; templateHtml: string; lines: QuotationLine[] };
const emptyLine = (): QuotationLine => ({ kind: "Service", description: "", quantity: 1, rate: 0, gstRate: 18 });
const money = (amount: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR" }).format(amount);
const totals = (lines: QuotationLine[], discount: number) => { const subtotal = lines.reduce((sum, line) => sum + line.quantity * line.rate, 0); const gst = lines.reduce((sum, line) => sum + Math.max(0, line.quantity * line.rate - (subtotal ? discount * (line.quantity * line.rate / subtotal) : 0)) * line.gstRate / 100, 0); return { subtotal, gst, total: Math.max(0, subtotal - discount) + gst }; };

function CatalogDescriptionCombobox({ lineNumber, value, tasks, onChange, onSelect }: { lineNumber: number; value: string; tasks: ServiceTask[]; onChange: (description: string) => void; onSelect: (task: ServiceTask) => void }) {
  const [open, setOpen] = useState(false); const [activeIndex, setActiveIndex] = useState(0); const listId = useId();
  const needle = value.trim().toLowerCase(); const matches = tasks.filter((task) => !needle || `${task.name} ${task.description ?? ""}`.toLowerCase().includes(needle)).slice(0, 100);
  const choose = (task: ServiceTask) => { onSelect(task); setOpen(false); };
  const openOptions = () => { setOpen(true); setActiveIndex(0); };
  return <label className="search-select quotation-catalog-description"><span className="sr-only">Catalog description for line {lineNumber}</span><input required role="combobox" aria-label={`Catalog description for line ${lineNumber}`} aria-expanded={open} aria-controls={listId} aria-activedescendant={open && matches[activeIndex] ? `${listId}-${matches[activeIndex].id}` : undefined} aria-autocomplete="list" placeholder="Type a description or search catalog" value={value} onFocus={openOptions} onClick={() => !open && openOptions()} onChange={(event) => { onChange(event.target.value); openOptions(); }} onBlur={() => window.setTimeout(() => setOpen(false), 120)} onKeyDown={(event) => { if (event.key === "ArrowDown" || event.key === "ArrowUp") { event.preventDefault(); setOpen(true); setActiveIndex((index) => event.key === "ArrowDown" ? Math.min(index + 1, Math.max(matches.length - 1, 0)) : Math.max(index - 1, 0)); } else if (event.key === "Enter" && open && matches[activeIndex]) { event.preventDefault(); choose(matches[activeIndex]); } else if (event.key === "Escape") { event.preventDefault(); setOpen(false); } }} />
    {open && <ul id={listId} role="listbox" aria-label={`Catalog suggestions for line ${lineNumber}`} className="search-select-options">{matches.length ? matches.map((task, index) => <li id={`${listId}-${task.id}`} key={task.id} role="option" aria-selected={index === activeIndex}><button type="button" onMouseDown={(event) => event.preventDefault()} onClick={() => choose(task)}>{task.name} · {money(task.rate)} · GST {task.gstRate}%</button></li>) : <li className="picker-stock" role="status">No catalog matches — your description will be saved as entered.</li>}</ul>}
  </label>;
}

export function QuotationEditorDialog({ config, leads, templates, quotation, tasks: suppliedTasks, busy, onClose, onSave }: { config?: CognitoConfig; leads: Lead[]; templates: Template[]; quotation?: Quotation; tasks?: ServiceTask[]; busy: boolean; onClose: () => void; onSave: (input: QuotationInput) => void }) {
  const defaultTemplate = templates.find((template) => template.active)?.id ?? templates[0]?.id ?? "";
  const [leadId, setLeadId] = useState(quotation?.leadId ?? 0); const [validUntil, setValidUntil] = useState(quotation?.validUntil ?? ""); const [notes, setNotes] = useState(quotation?.customerNotes ?? ""); const [discount, setDiscount] = useState(String(quotation?.discount ?? 0)); const [templateId, setTemplateId] = useState(quotation?.templateId ?? defaultTemplate);
  const [lines, setLines] = useState<QuotationLine[]>(quotation?.lines.length ? quotation.lines : [emptyLine()]); const [tasks, setTasks] = useState<ServiceTask[]>(suppliedTasks ?? []); const [catalogError, setCatalogError] = useState("");
  useEffect(() => { if (suppliedTasks) setTasks(suppliedTasks); else if (config) void salesApi.serviceTasks(config).then(setTasks).catch((error: unknown) => setCatalogError(error instanceof Error ? error.message : "SERVICE_TASKS_FAILED")); }, [config, suppliedTasks]);
  const amount = useMemo(() => totals(lines, Number(discount) || 0), [lines, discount]);
  const changeLine = (index: number, patch: Partial<QuotationLine>) => setLines((current) => current.map((line, lineIndex) => lineIndex === index ? { ...line, ...patch } : line));
  const selectTask = (index: number, task: ServiceTask) => changeLine(index, { kind: "Service", description: task.description || task.name, rate: task.rate, gstRate: task.gstRate });
  const selectTemplate = (id: string) => setTemplateId(id);
  const submit = (event: FormEvent) => { event.preventDefault(); const cleanLines = lines.filter((line) => line.description.trim()); const templateHtml = templates.find((template) => template.id === templateId)?.html ?? ""; if (!leadId || !templateId || !templateHtml.trim() || !cleanLines.length) return; onSave({ leadId, validUntil: validUntil || undefined, customerNotes: notes, discount: Number(discount) || 0, templateId, templateHtml, lines: cleanLines }); };
  return <Dialog wide title={quotation ? "Edit quotation" : "New quotation"} subtitle={quotation ? `${quotation.quotationNo} · Draft` : "Create a frozen quotation document"} onClose={onClose} className="dialog-document-editor" footer={<button className="primary-action" type="submit" form="quotation-editor-form" disabled={busy}>{quotation ? "Save quotation" : "Create quotation"}</button>}><form id="quotation-editor-form" className="billing-dialog-form" onSubmit={submit}>
    <div className="form-grid"><label>Lead<select data-dialog-initial-focus required value={leadId} onChange={(event) => setLeadId(Number(event.target.value))}><option value={0}>Select lead</option>{leads.map((lead) => <option key={lead.id} value={lead.id}>{lead.displayName} · {lead.phone}</option>)}</select></label><label>Valid until<input type="date" value={validUntil} onChange={(event) => setValidUntil(event.target.value)} /></label><label>Template<select required value={templateId} onChange={(event) => selectTemplate(event.target.value)}>{templates.map((template) => <option key={template.id} value={template.id}>{template.name}{template.active ? " (Active)" : ""}</option>)}</select></label><label>Discount<input type="number" min="0" value={discount} onChange={(event) => setDiscount(event.target.value)} /></label></div>
    <label>Customer notes<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label>
    <div className="estimate-items"><div className="line-items-header"><strong>Line items</strong><button type="button" className="add-line-item" onClick={() => setLines((current) => [...current, emptyLine()])}><Plus size={16} />Add Item</button></div>{catalogError && <p className="error-text" role="alert">Service catalog unavailable: {catalogError}</p>}<div className="estimate-item estimate-item-heading quotation-item-heading"><span>Catalog description</span><span>Quantity</span><span>Rate</span><span>GST rate</span><span>Action</span></div>{lines.map((line, index) => <div className="estimate-item quotation-item" key={line.id ?? index}><CatalogDescriptionCombobox lineNumber={index + 1} value={line.description} tasks={tasks} onChange={(description) => changeLine(index, { description })} onSelect={(task) => selectTask(index, task)} /><input aria-label={`Quantity for line ${index + 1}`} type="number" min="0.001" step="0.001" required value={line.quantity} onChange={(event) => changeLine(index, { quantity: Number(event.target.value) })} /><input aria-label={`Rate for line ${index + 1}`} type="number" min="0" required value={line.rate} onChange={(event) => changeLine(index, { rate: Number(event.target.value) })} /><input aria-label={`GST rate for line ${index + 1}`} type="number" min="0" max="100" required value={line.gstRate} onChange={(event) => changeLine(index, { gstRate: Number(event.target.value) })} /><button type="button" className="link-action line-remove" aria-label={`Remove quotation item ${index + 1}`} onClick={() => setLines((current) => current.length > 1 ? current.filter((_, lineIndex) => lineIndex !== index) : [emptyLine()])}>Remove</button></div>)}</div>
    <div className="document-totals"><span>Subtotal {money(amount.subtotal)}</span><span>Discount {money(Number(discount) || 0)}</span><span>GST {money(amount.gst)}</span><strong>Total {money(amount.total)}</strong></div>
  </form></Dialog>;
}

export function quotationDocumentHtml(document: QuotationDocument) { const snapshot = document.snapshot; const total = Number(snapshot.total ?? 0); const lines: ReportLine[] = (snapshot.lines ?? []).map((line) => ({ kind: line.kind, description: line.description, qty: String(line.quantity), rate: money(line.rate), amount: money(line.quantity * line.rate) })); return renderReportTemplate({ html: document.templateHtml, category: "quotation" }, { "report.title": "Quotation", "report.number": document.quotationNo, "report.date": new Date(document.createdAt).toLocaleDateString("en-IN"), "customer.name": snapshot.leadName ?? "—", "customer.mobile": snapshot.phone ?? "—", "quotation.valid_until": snapshot.validUntil ?? "—", "quotation.notes": snapshot.customerNotes ?? "", "report.subtotal": money(Number(snapshot.subtotal ?? 0)), "report.discount": money(Number(snapshot.discount ?? 0)), "report.gst": money(Number(snapshot.gstAmount ?? 0)), "quotation.total": money(total), "report.amount_words": rupeesInWords(total) }, lines); }

export function QuotationOutputControls({ loadDocument, onError, className, buttonClassName }: { loadDocument: () => Promise<QuotationDocument>; onError?: (message: string) => void; className?: string; buttonClassName?: string }) { const [busy, setBusy] = useState<"" | "download" | "print">(""); const run = async (action: "download" | "print") => { setBusy(action); onError?.(""); try { const document = await loadDocument(); const html = quotationDocumentHtml(document); if (action === "download") await renderHtmlToPdf(html, `${document.quotationNo}.pdf`); else { const result = printRenderedDocument({ html, title: `Quotation ${document.quotationNo}` }); if (!result.ok) throw new Error(result.error); } } catch (error) { onError?.(error instanceof Error ? error.message : "QUOTATION_OUTPUT_FAILED"); } finally { setBusy(""); } }; return <span className={className}><button type="button" className={buttonClassName} disabled={Boolean(busy)} aria-busy={Boolean(busy)} onClick={() => void run("download")}><Download size={15} />{busy === "download" ? "Generating PDF…" : "Download PDF"}</button><button type="button" className={buttonClassName} disabled={Boolean(busy)} aria-busy={Boolean(busy)} onClick={() => void run("print")}><Printer size={15} />{busy === "print" ? "Preparing print…" : "Print"}</button></span>; }
export function QuotationDownloadButton({ config, quotationId, className, buttonClassName, onError }: { config: CognitoConfig; quotationId: number; className?: string; buttonClassName?: string; onError?: (message: string) => void }) { return <QuotationOutputControls className={className} buttonClassName={buttonClassName} loadDocument={() => salesApi.document(config, quotationId)} onError={onError} />; }
export function QuotationDetailsDialog({ config, quotation, lead, templateName, loadDocument, onClose }: { config?: CognitoConfig; quotation: Quotation; lead?: Lead; templateName: string; loadDocument?: () => Promise<QuotationDocument>; onClose: () => void }) { const [error, setError] = useState(""); const document = loadDocument ?? (() => config ? salesApi.document(config, quotation.id) : Promise.reject(new Error("QUOTATION_DOCUMENT_UNAVAILABLE"))); return <Dialog wide title={`Quotation ${quotation.quotationNo}`} subtitle="Read-only frozen quotation" onClose={onClose} footer={<QuotationOutputControls loadDocument={document} onError={setError} />}>{error && <p className="error-text" role="alert">{error}</p>}<div className="form-grid"><p><strong>Customer</strong><br />{lead?.displayName ?? quotation.leadId}<br />{lead?.phone}</p><p><strong>Status</strong><br />{quotation.status}</p><p><strong>Valid until</strong><br />{quotation.validUntil ?? "—"}</p><p><strong>Template</strong><br />{templateName}</p></div><div className="table-wrap"><table aria-label="Quotation details"><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>GST</th><th>Amount</th></tr></thead><tbody>{quotation.lines.map((line, index) => <tr key={line.id ?? index}><td>{line.description}</td><td>{line.quantity}</td><td>{money(line.rate)}</td><td>{line.gstRate}%</td><td>{money(line.quantity * line.rate)}</td></tr>)}</tbody></table></div>{quotation.customerNotes && <p><strong>Notes</strong><br />{quotation.customerNotes}</p>}<div className="document-totals"><span>Subtotal {money(quotation.subtotal)}</span><span>Discount {money(quotation.discount)}</span><span>GST {money(quotation.gstAmount)}</span><strong>Total {money(quotation.total)}</strong></div></Dialog>; }
