import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { CognitoConfig } from "./auth";
import { loadAdminDemoState } from "./admin-demo-state";
import { SalesLeadDialog, blankLeadDraft, type LeadFormDraft } from "./sales-lead-dialog";
import { salesApi, type Lead, type QuotationLine } from "./sales-api";

type LeadInput = Omit<Lead, "id" | "branchId" | "createdAt" | "updatedAt">;
const leadDraft = (lead: Lead): LeadFormDraft => ({ displayName: lead.displayName, phone: lead.phone, company: lead.company, email: lead.email, address: lead.address, serviceInterest: lead.serviceInterest, notes: lead.notes, stage: lead.stage, temperature: lead.temperature, followUpDue: lead.followUpDue, siteVisitCompleted: lead.siteVisitCompleted, siteVisitDate: lead.siteVisitDate });

export function RemoteSalesWorkspace({ config, mode }: { config: CognitoConfig; mode: "leads" | "quotations" }) {
  const [leads, setLeads] = useState<Lead[]>([]); const [quotations, setQuotations] = useState<Awaited<ReturnType<typeof salesApi.quotations>>>([]); const [query, setQuery] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [leadDialog, setLeadDialog] = useState<"add" | "edit" | null>(null); const [selectedLead, setSelectedLead] = useState<Lead | null>(null);
  const templates = useMemo(() => loadAdminDemoState().reportTemplates.filter((item) => item.category === "quotation"), []);
  const refresh = async () => { const filter = query ? `?q=${encodeURIComponent(query)}` : ""; const [nextLeads, nextQuotations] = await Promise.all([salesApi.leads(config, filter), salesApi.quotations(config, filter)]); setLeads(nextLeads); setQuotations(nextQuotations); };
  useEffect(() => { void refresh().catch((caught) => setError(caught instanceof Error ? caught.message : "SALES_CRM_API_FAILED")); }, [config]);
  const run = (action: () => Promise<unknown>, after?: () => void) => { setBusy(true); setError(""); void action().then(async () => { after?.(); await refresh(); }).catch((caught) => setError(caught instanceof Error ? caught.message : "SALES_CRM_API_FAILED")).finally(() => setBusy(false)); };
  const closeLeadDialog = () => { setLeadDialog(null); setSelectedLead(null); };
  const saveLead = (draft: LeadFormDraft) => { const input: LeadInput = draft; run(() => leadDialog === "edit" && selectedLead ? salesApi.updateLead(config, selectedLead.id, input) : salesApi.createLead(config, input), closeLeadDialog); };
  if (mode === "leads") return <section className="workspace single-panel"><div className="desk-panel"><div className="panel-actions"><div><h2>Sales Leads</h2><p>Admin-only inquiries, follow-ups, and site visits.</p></div><button className="primary-action" onClick={() => { setSelectedLead(null); setLeadDialog("add"); }}>New Lead</button></div>{error && <p className="api-error" role="alert">{error}</p>}<div className="store-filter-grid"><label className="list-search">Search leads<input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => event.key === "Enter" && void refresh()} placeholder="Name, company, or phone" /></label><button onClick={() => void refresh()} disabled={busy}>Apply</button></div>{leadDialog && <SalesLeadDialog lead={selectedLead ? leadDraft(selectedLead) : blankLeadDraft} editing={leadDialog === "edit"} busy={busy} onSave={saveLead} onClose={closeLeadDialog} />}<div className="table-wrap"><table aria-label="Sales leads"><thead><tr><th>Lead</th><th>Contact</th><th>Stage</th><th>Temperature</th><th>Follow-up</th><th>Site visit</th><th>Actions</th></tr></thead><tbody>{leads.map((item) => <tr key={item.id} className={`sales-temperature-${item.temperature.toLowerCase()}`}><td><strong>{item.displayName}</strong><br/>{item.company || "—"}</td><td>{item.phone}<br/>{item.email || "—"}</td><td>{item.stage.replaceAll("_", " ")}</td><td>{item.temperature}</td><td>{item.followUpDue || "—"}</td><td>{item.siteVisitCompleted ? item.siteVisitDate || "Complete" : "Pending"}</td><td><button disabled={busy} onClick={() => { setSelectedLead(item); setLeadDialog("edit"); }}>Edit</button></td></tr>)}</tbody></table></div>{!leads.length && <p className="empty-state">No leads match these filters.</p>}</div></section>;
  return <QuotationWorkspace config={config} leads={leads} quotations={quotations} templates={templates} error={error} busy={busy} refresh={refresh} run={run} />;
}
function QuotationWorkspace({ config, leads, quotations, templates, error, busy, refresh, run }: { config:CognitoConfig; leads:Lead[]; quotations:Awaited<ReturnType<typeof salesApi.quotations>>; templates:ReturnType<typeof loadAdminDemoState>["reportTemplates"]; error:string; busy:boolean; refresh:()=>Promise<void>; run:(a:()=>Promise<unknown>, after?:()=>void)=>void }) {
  const [open,setOpen]=useState(false); const [leadId,setLeadId]=useState(0); const [validUntil,setValidUntil]=useState(""); const [discount,setDiscount]=useState("0"); const [description,setDescription]=useState(""); const [rate,setRate]=useState(""); const [templateId,setTemplateId]=useState(templates.find((t)=>t.active)?.id ?? templates[0]?.id ?? ""); const [lines,setLines]=useState<QuotationLine[]>([]);
  const add=()=>{ if (!description.trim()) return; setLines([...lines,{kind:"Service",description:description.trim(),quantity:1,rate:Number(rate)||0,gstRate:18}]); setDescription("");setRate(""); };
  const create=(event:FormEvent)=>{event.preventDefault(); const template=templates.find((item)=>item.id===templateId); if(!leadId||!template||!lines.length)return; run(()=>salesApi.createQuotation(config,{leadId,validUntil:validUntil||undefined,discount:Number(discount)||0,templateId:template.id,templateHtml:template.html,lines}),()=>{setOpen(false);setLines([]);});};
  return <section className="workspace single-panel"><div className="desk-panel"><div className="panel-actions"><div><h2>Quotations</h2><p>Frozen quotation documents and their lifecycle.</p></div><button className="primary-action" onClick={()=>setOpen(true)}>New Quotation</button></div>{error&&<p className="api-error" role="alert">{error}</p>}{open&&<form className="form-grid" onSubmit={create}><h3>Create quotation</h3><label>Lead<select required value={leadId} onChange={(e)=>setLeadId(Number(e.target.value))}><option value={0}>Select lead</option>{leads.map((lead)=><option key={lead.id} value={lead.id}>{lead.displayName} · {lead.phone}</option>)}</select></label><label>Validity<input type="date" value={validUntil} onChange={(e)=>setValidUntil(e.target.value)}/></label><label>Discount<input type="number" min="0" value={discount} onChange={(e)=>setDiscount(e.target.value)}/></label><label>Template<select required value={templateId} onChange={(e)=>setTemplateId(e.target.value)}>{templates.map((template)=><option key={template.id} value={template.id}>{template.name}{template.active?" (Active)":""}</option>)}</select></label><label>Line description<input value={description} onChange={(e)=>setDescription(e.target.value)}/></label><label>Base rate<input type="number" min="0" value={rate} onChange={(e)=>setRate(e.target.value)}/></label><button type="button" onClick={add}>Add line</button>{lines.map((line,index)=><p key={`${line.description}-${index}`}>{line.description} · ₹{line.rate.toFixed(2)} <button type="button" onClick={()=>setLines(lines.filter((_,i)=>i!==index))}>Remove</button></p>)}<div className="action-row"><button className="primary-action" disabled={busy||!lines.length}>Create quotation</button><button type="button" onClick={()=>setOpen(false)}>Cancel</button></div></form>}<div className="table-wrap"><table aria-label="Quotation register"><thead><tr><th>Number</th><th>Lead</th><th>Status</th><th>Amount</th><th>Valid until</th><th>Actions</th></tr></thead><tbody>{quotations.map((item)=><tr key={item.id}><td>{item.quotationNo}</td><td>{leads.find((lead)=>lead.id===item.leadId)?.displayName ?? item.leadId}</td><td>{item.status}</td><td>₹{item.total.toFixed(2)}</td><td>{item.validUntil||"—"}</td><td><button disabled={busy||["ACCEPTED","REJECTED","EXPIRED"].includes(item.status)} onClick={()=>run(()=>salesApi.status(config,item.id,"SENT"))}>Mark sent</button> <button disabled={busy||item.status!=="SENT"} onClick={()=>run(()=>salesApi.status(config,item.id,"ACCEPTED"))}>Accept</button></td></tr>)}</tbody></table></div><button onClick={()=>void refresh()} disabled={busy}>Refresh</button></div></section>;
}
