import { Check, Eye, Pencil, Send } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { CognitoConfig } from "./auth";
import { loadAdminDemoState } from "./admin-demo-state";
import { SalesLeadDialog, blankLeadDraft, type LeadFormDraft } from "./sales-lead-dialog";
import { salesApi, type Lead, type Quotation, type QuotationStatus } from "./sales-api";
import { QuotationFilterBar } from "./quotation-filter-bar";
import { QuotationDetailsDialog, QuotationDownloadButton, QuotationEditorDialog } from "./quotation-dialog";
import { DownloadMenu } from "./ui-kit";
import { leadDraft, leadFilterQuery, salesLeadsReport, SalesLeadFilterBar, SalesLeadRegister } from "./sales-lead-register";

type LeadInput = Omit<Lead, "id" | "branchId" | "createdAt" | "updatedAt">;
const currentMonthYear = () => {
  const date = new Date();
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}`;
};

export function RemoteSalesWorkspace({ config, mode }: { config: CognitoConfig; mode: "leads" | "quotations" }) {
  const [leads, setLeads] = useState<Lead[]>([]); const [quotations, setQuotations] = useState<Quotation[]>([]); const [query, setQuery] = useState(""); const [stage, setStage] = useState<Lead["stage"] | "">(""); const [createdDate, setCreatedDate] = useState(""); const [createdMonth, setCreatedMonth] = useState(currentMonthYear); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [leadDialog, setLeadDialog] = useState<"add" | "edit" | null>(null); const [selectedLead, setSelectedLead] = useState<Lead | null>(null);
  const templates = useMemo(() => loadAdminDemoState().reportTemplates.filter((item) => item.category === "quotation"), []);
  const quotationParams = new URLSearchParams(); if (query.trim()) quotationParams.set("q", query.trim()); if (createdDate) quotationParams.set("exactDate", createdDate); else if (createdMonth) quotationParams.set("month", createdMonth); const quotationFilters = quotationParams.size ? `?${quotationParams}` : "";
  const refresh = async () => { const leadFilter = mode === "leads" ? leadFilterQuery(query, stage, createdMonth) : ""; const [nextLeads, nextQuotations] = await Promise.all([salesApi.leads(config, leadFilter), salesApi.quotations(config, mode === "quotations" ? quotationFilters : "")]); setLeads(nextLeads); setQuotations(nextQuotations); };
  useEffect(() => { void refresh().catch((caught) => setError(caught instanceof Error ? caught.message : "SALES_CRM_API_FAILED")); }, [config, mode, query, stage, createdDate, createdMonth]);
  const run = (action: () => Promise<unknown>, after?: () => void) => { setBusy(true); setError(""); void action().then(async () => { after?.(); await refresh(); }).catch((caught) => setError(caught instanceof Error ? caught.message : "SALES_CRM_API_FAILED")).finally(() => setBusy(false)); };
  const closeLeadDialog = () => { setLeadDialog(null); setSelectedLead(null); };
  const saveLead = (draft: LeadFormDraft) => { const input: LeadInput = draft; run(() => leadDialog === "edit" && selectedLead ? salesApi.updateLead(config, selectedLead.id, input) : salesApi.createLead(config, input), closeLeadDialog); };
  const saveInlineLead = async (lead: Lead, draft: LeadFormDraft) => { setBusy(true); setError(""); try { await salesApi.updateLead(config, lead.id, draft); await refresh(); return true; } catch (caught) { setError(caught instanceof Error ? caught.message : "SALES_CRM_API_FAILED"); return false; } finally { setBusy(false); } };
  if (mode === "leads") return <section className="workspace single-panel"><div className="desk-panel"><div className="panel-actions"><div><h2>Sales Leads</h2><p>Admin-only inquiries, follow-ups, and site visits.</p></div><div className="grid-actions"><DownloadMenu report={salesLeadsReport(leads, createdMonth, query, stage)} /><button className="primary-action" onClick={() => { setSelectedLead(null); setLeadDialog("add"); }}>Add Lead</button></div></div>{error && <p className="api-error" role="alert">{error}</p>}<SalesLeadFilterBar query={query} stage={stage} createdMonth={createdMonth} busy={busy} onQueryChange={setQuery} onStageChange={setStage} onCreatedMonthChange={setCreatedMonth} onClear={() => { setQuery(""); setStage(""); setCreatedMonth(""); }} />{leadDialog && <SalesLeadDialog lead={selectedLead ? leadDraft(selectedLead) : blankLeadDraft} editing={leadDialog === "edit"} busy={busy} onSave={saveLead} onClose={closeLeadDialog} />}<SalesLeadRegister leads={leads} busy={busy} onEdit={(lead) => { setSelectedLead(lead); setLeadDialog("edit"); }} onSave={saveInlineLead} /></div></section>;
  return <QuotationWorkspace config={config} leads={leads} quotations={quotations} templates={templates} error={error} busy={busy} query={query} onQueryChange={setQuery} createdDate={createdDate} onCreatedDateChange={setCreatedDate} createdMonth={createdMonth} onCreatedMonthChange={setCreatedMonth} run={run} />;
}

function QuotationWorkspace({ config, leads, quotations, templates, error, busy, query, onQueryChange, createdDate, onCreatedDateChange, createdMonth, onCreatedMonthChange, run }: { config: CognitoConfig; leads: Lead[]; quotations: Quotation[]; templates: ReturnType<typeof loadAdminDemoState>["reportTemplates"]; error: string; busy: boolean; query: string; onQueryChange: (query: string) => void; createdDate: string; onCreatedDateChange: (date: string) => void; createdMonth: string; onCreatedMonthChange: (month: string) => void; run: (action: () => Promise<unknown>, after?: () => void) => void }) {
  const status = ""; const onStatusChange = undefined;
  const [editor, setEditor] = useState<Quotation | "new" | null>(null); const [details, setDetails] = useState<Quotation | null>(null); const [documentError, setDocumentError] = useState("");
  const filteredQuotations = quotations.filter((item) => {
    const searchable = `${item.quotationNo} ${leads.find((lead) => lead.id === item.leadId)?.displayName ?? ""}`.toLowerCase();
    return (!query || searchable.includes(query.trim().toLowerCase())) && (!createdDate || item.createdAt.slice(0, 10) === createdDate) && (!createdDate && createdMonth ? item.createdAt.startsWith(createdMonth) : true);
  });
  const clearFilters = () => { onQueryChange(""); onCreatedDateChange(""); onCreatedMonthChange(""); };
  return <section className="workspace single-panel"><div className="desk-panel"><div className="panel-actions"><div><h2>Quotations</h2><p>Frozen quotation documents and their lifecycle.</p></div><button className="primary-action" onClick={() => setEditor("new")}>New Quotation</button></div>{(error || documentError) && <p className="api-error" role="alert">{error || documentError}</p>}{editor && <QuotationEditorDialog config={config} leads={leads} templates={templates} quotation={editor === "new" ? undefined : editor} busy={busy} onClose={() => setEditor(null)} onSave={(input) => run(() => editor !== "new" ? salesApi.updateQuotation(config, editor.id, input) : salesApi.createQuotation(config, input), () => setEditor(null))} />}{details && <QuotationDetailsDialog config={config} quotation={details} lead={leads.find((lead) => lead.id === details.leadId)} templateName={templates.find((template) => template.id === details.templateId)?.name ?? details.templateId} onClose={() => setDetails(null)} />}<QuotationFilterBar query={query} status={status} createdDate={createdDate} createdMonth={createdMonth} busy={busy} onQueryChange={onQueryChange} onStatusChange={onStatusChange} onCreatedDateChange={onCreatedDateChange} onCreatedMonthChange={onCreatedMonthChange} onClear={clearFilters} /><div className="table-wrap sales-crm-table"><table aria-label="Quotation register"><thead><tr><th>Number</th><th>Lead</th><th>Status</th><th>Amount</th><th>Created</th><th>Valid until</th><th>Actions</th></tr></thead><tbody>{filteredQuotations.map((item) => <tr key={item.id}><td>{item.quotationNo}</td><td>{leads.find((lead) => lead.id === item.leadId)?.displayName ?? item.leadId}</td><td>{item.status}</td><td>₹{item.total.toFixed(2)}</td><td>{item.createdAt.slice(0, 10)}</td><td>{item.validUntil || "—"}</td><td><div className="grid-actions billing-table-actions"><button type="button" className="billing-table-action" onClick={() => setDetails(item)}><Eye size={15} />View details</button>{item.status === "DRAFT" && <button type="button" className="billing-table-action" disabled={busy} onClick={() => setEditor(item)}><Pencil size={15} />Edit</button>}<QuotationDownloadButton config={config} quotationId={item.id} className="quotation-document-actions" buttonClassName="billing-table-action" onError={setDocumentError} /><button type="button" className="billing-table-action billing-table-action-primary" disabled={busy || ["ACCEPTED", "REJECTED", "EXPIRED"].includes(item.status)} onClick={() => run(() => salesApi.status(config, item.id, "SENT"))}><Send size={15} />Mark sent</button><button type="button" className="billing-table-action" disabled={busy || item.status !== "SENT"} onClick={() => run(() => salesApi.status(config, item.id, "ACCEPTED"))}><Check size={15} />Accept</button></div></td></tr>)}</tbody></table></div>{!filteredQuotations.length && <p className="empty-state">No quotations match these filters.</p>}</div></section>;
}
